<?php
return [
    'key' => 'view_editor',
    'name' => 'View Editor',
    'name_key' => 'studio.tool.view_editor.name',
    'description_key' => 'studio.tool.view_editor.description',
    'category' => 'authoring',
    'home_group' => 'composition',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/view-editor',
    'placeholder' => true,
    'risk_level' => 'medium',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/view-editor'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['view', 'dashboard', 'surface', 'component'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
