<?php
return [
    'tool_key' => 'css_live_editor',
    'key' => 'css_live_editor',
    'label' => 'CSS Live Editor',
    'name' => 'CSS Live Editor',
    'name_key' => 'studio.tool.css_live_editor.name',
    'description_key' => 'studio.tool.css_live_editor.description',
    'category' => 'authoring',
    'home_group' => 'design_content',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/customization-studio/advanced/css-live-editor',
    'placeholder' => false,
    'risk_level' => 'read_only',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/customization-studio/advanced/css-live-editor',
        '/apps/studio/tools/customization-studio/advanced/css-live-editor/preview-frame',
    ],
    'views' => [
        'apps/Studio/Tools/CustomizationStudio/Advanced/CssLiveEditor/cssliveditor.php',
        'apps/Studio/Tools/CustomizationStudio/Advanced/CssLiveEditor/preview-frame.php',
    ],
    'services' => [
        'Apps\\Studio\\Controllers\\StudioController::cssLiveEditorPlaceholder',
        'Apps\\Studio\\Controllers\\StudioController::cssLiveEditorPreviewFrame',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorPlaceholderService::model',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorTargetService::resolve',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorPreviewSanitizer::policy',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorSourceResolver::resolveRoute',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorStyleSourceService::catalog',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorCssSourceService::catalog',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorTemplateTargetService::targets',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Advanced\\CssLiveEditor\\Services\\CssLiveEditorTemplateRenderer::render',
    ],
    'owner' => 'studio',
    'can_load' => ['page', 'view', 'component'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => false,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
