CREATE TABLE IF NOT EXISTS user_app_roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    app_key VARCHAR(120) NOT NULL,
    operational_role VARCHAR(120) NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_user_app (user_id, app_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
