<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'hospitality',
    'items' => [
        [
            'source_key' => 'apps.hospitality.home',
            'group' => 'Apps',
            'section' => 'Hospitality',
            'module' => 'hospitality',
            'owner' => 'hospitality',
            'key' => 'hospitality_home',
            'feature_key' => 'hospitality_home',
            'label' => 'Hospitality',
            'url' => '/apps/hospitality',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 10,
            'priority' => 80,
        ],
        [
            'source_key' => 'apps.hospitality.rooms',
            'group' => 'Apps',
            'section' => 'Hospitality',
            'module' => 'rooms',
            'owner' => 'hospitality',
            'key' => 'rooms_index',
            'feature_key' => 'rooms_index',
            'label' => 'Rooms',
            'url' => '/apps/hospitality/rooms',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 20,
            'priority' => 78,
        ],
        [
            'source_key' => 'apps.hospitality.guests',
            'group' => 'Apps',
            'section' => 'Hospitality',
            'module' => 'guests',
            'owner' => 'hospitality',
            'key' => 'guests_index',
            'feature_key' => 'guests_index',
            'label' => 'Guests',
            'url' => '/apps/hospitality/guests',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 30,
            'priority' => 76,
        ],
        [
            'source_key' => 'apps.hospitality.reservations',
            'group' => 'Apps',
            'section' => 'Hospitality',
            'module' => 'reservations',
            'owner' => 'hospitality',
            'key' => 'reservations_index',
            'feature_key' => 'reservations_index',
            'label' => 'Reservations',
            'url' => '/apps/hospitality/reservations',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 40,
            'priority' => 74,
        ],
        [
            'source_key' => 'apps.hospitality.front_desk',
            'group' => 'Apps',
            'section' => 'Hospitality',
            'module' => 'front_desk',
            'owner' => 'hospitality',
            'key' => 'front_desk_index',
            'feature_key' => 'front_desk_index',
            'label' => 'Front Desk',
            'url' => '/apps/hospitality/front-desk',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 50,
            'priority' => 72,
        ],
        [
            'source_key' => 'apps.hospitality.housekeeping',
            'group' => 'Apps',
            'section' => 'Hospitality',
            'module' => 'housekeeping',
            'owner' => 'hospitality',
            'key' => 'housekeeping_index',
            'feature_key' => 'housekeeping_index',
            'label' => 'Housekeeping',
            'url' => '/apps/hospitality/housekeeping',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 60,
            'priority' => 70,
        ],
    ],
];
