<?php
return [
    'key' => 'engineering_workspaces',
    'name' => 'Engineering Workspaces',
    'name_key' => 'studio.tool.engineering_workspaces.name',
    'description_key' => 'studio.tool.engineering_workspaces.description',
    'category' => 'governance',
    'home_group' => 'governance',
    'status' => 'available',
    'canonical_route' => '/apps/studio/tools/engineering-workspaces',
    'engineering_workspace' => [
        'surface_classification' => 'non_workspace',
    ],
    'placeholder' => false,
    'risk_level' => 'guarded_mutation',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/engineering-workspaces',
        '/apps/studio/tools/engineering-workspaces/provision/preview',
        '/apps/studio/tools/engineering-workspaces/provision/apply',
        '/apps/studio/tools/engineering-workspaces/provision/rollback',
        '/apps/studio/tools/engineering-workspaces/deploy/create',
        '/apps/studio/tools/engineering-workspaces/deploy/replace',
        '/apps/studio/tools/engineering-workspaces/deploy/restore',
        '/apps/studio/tools/engineering-workspaces/deploy/create-missing-all',
        '/apps/studio/tools/engineering-workspaces/new-workspace',
        '/apps/studio/tools/engineering-workspaces/coverage-assign',
    ],
    'views' => ['apps/Studio/Tools/EngineeringWorkspaces/Views/preview.php'],
    'services' => [
        'Apps\\Studio\\Tools\\EngineeringWorkspaces\\Services\\EngineeringWorkspaceHubService',
        'Apps\\Studio\\Tools\\EngineeringWorkspaces\\Services\\EngineeringWorkspaceCoverageService',
        'Apps\\Studio\\Tools\\EngineeringWorkspaces\\Services\\EngineeringWorkspaceProvisioningService',
        'Apps\\Studio\\Tools\\EngineeringWorkspaces\\Services\\EngineeringWorkspaceCoverageAssignmentService',
        'Platform\\Security\\EngineeringWorkspaceContentContract',
    ],
    'owner' => 'studio',
    'can_load' => ['engineering_workspace'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
