<?php
return [
    'key' => 'validation_center',
    'name' => 'Validation Center',
    'name_key' => 'studio.tool.validation_center.name',
    'description_key' => 'studio.tool.validation_center.description',
    'category' => 'validation',
    'home_group' => 'governance',
    'status' => 'available',
    'canonical_route' => '/apps/studio/workflow/analyze',
    'placeholder' => false,
    'risk_level' => 'read_only',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/workflow/analyze'],
    'views' => ['apps/Studio/Views/pages/workflow_stage.php'],
    'services' => ['Apps\\Studio\\Services\\StudioGovernanceService'],
    'owner' => 'studio',
    'can_load' => ['app', 'module', 'view', 'dashboard', 'route', 'nav', 'theme', 'widget', 'report', 'package'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => true,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
