<?php
return [
    'tool_key' => 'change_control_center',
    'key' => 'change_control_center',
    'label' => 'Change Control Center',
    'name' => 'Change Control Center',
    'name_key' => 'studio.tool.change_control_center.name',
    'description_key' => 'studio.tool.change_control_center.description',
    'category' => 'governance',
    'home_group' => 'governance',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/change-control-center',
    'placeholder' => true,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/change-control-center'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['change_record', 'diff', 'approval', 'snapshot', 'handover'],
    'can_modify' => false,
    'requires_approval' => true,
    'writes_to_owner_artifact' => false,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
