<?php
return [
    'tool_key' => 'style_compliance',
    'key' => 'style_compliance',
    'label' => 'Style Compliance',
    'name' => 'Style Compliance',
    'name_key' => 'studio.tool.style_compliance.name',
    'description_key' => 'studio.tool.style_compliance.description',
    'category' => 'governance',
    'home_group' => 'governance',
    'canonical_route' => '/apps/studio/tools/customization-studio/diagnose/style-compliance',
    'placeholder' => false,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.tools.style_compliance.use'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/customization-studio/diagnose/style-compliance',
        '/apps/studio/tools/customization-studio/diagnose/style-compliance/scan',
        '/apps/studio/tools/customization-studio/diagnose/style-compliance/repair-readiness',
        '/apps/studio/tools/customization-studio/diagnose/style-compliance/fix-one',
        '/apps/studio/tools/customization-studio/diagnose/style-compliance/repair-execute',
    ],
    'views' => ['apps/Studio/Tools/CustomizationStudio/Diagnose/StyleCompliance/Views/preview.php'],
    'services' => [
        'Apps\\Studio\\Tools\\CustomizationStudio\\Diagnose\\StyleCompliance\\Services\\StyleComplianceScannerService',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Diagnose\\StyleCompliance\\Services\\StyleComplianceGuardedRepairCapabilityService',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Diagnose\\StyleCompliance\\Services\\StyleComplianceRepairReadinessService',
        'Apps\\Studio\\Tools\\CustomizationStudio\\Diagnose\\StyleCompliance\\Services\\StyleComplianceRepairEngineService',
    ],
    'owner' => 'studio',
    'status' => 'active',
    'can_load' => ['css'],
    'can_modify' => true,
    'requires_approval' => false,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => false,
    'supports_rollback' => false,
    'capabilities' => [
        'evidence' => [
            'enabled' => true,
            'environments' => ['local', 'staging', 'production'],
        ],
        'guarded_repair' => [
            'enabled' => false,
            'environments' => ['local', 'staging'],
            'production_enabled' => false,
            'static_css_only' => true,
            'no_php_style_blocks' => true,
            'no_inline_html_styles' => true,
            'no_generated_minified_built_compiled_vendor_fixture_print_effect_sources' => true,
        ],
    ],
];