<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'manufacturing',
    'items' => [
        // Broad app-entry surface: keep untagged so Manufacturing home remains visible
        // regardless of single-lane module restrictions.
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'manufacturing_home',
            'feature_key' => 'manufacturing_portal',
            'label_key' => 'nav.manufacturing_portal',
            'label' => 'Manufacturing Workspace',
            'url' => '/apps/manufacturing',
            'visible_if' => 'role_supervisor',
            'nav_visible' => true,
            'order' => 10,
            'priority' => 100,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing'],
                'prefix' => ['/apps/manufacturing/'],
            ],
        ],
        // Cross-role coordination surface: intentionally untagged because it spans
        // multiple operational lanes and does not fit the current single-token model.
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'cross_role_handoff',
            'feature_key' => 'cross_role_handoff',
            'label_key' => 'nav.cross_role_handoff',
            'url' => '/apps/manufacturing/handoffs',
            'visible_if' => 'role_supervisor',
            'nav_visible' => true,
            'order' => 15,
            'priority' => 92,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/handoffs', '/ops/handoff-board'],
                'prefix' => ['/apps/manufacturing/handoffs/', '/ops/handoff-board/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'production_dashboard',
            'feature_key' => 'production_dashboard',
            'module_token' => 'production',
            'label_key' => 'nav.machine_leader',
            'label' => 'Production Workspace',
            'url' => '/apps/manufacturing/production-dashboard',
            'menu_key' => 'ipm.machine_leader',
            'visible_if' => 'role_machine_leader',
            'nav_visible' => true,
            'order' => 20,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/production-dashboard'],
                'prefix' => ['/apps/manufacturing/production-dashboard/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'production_operation',
            'feature_key' => 'production_operation',
            'module_token' => 'production',
            'label_key' => 'nav.production_operation',
            'label' => 'Production Operation',
            'url' => '/apps/manufacturing/production-operation',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 25,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/production-operation'],
                'prefix' => ['/apps/manufacturing/production-operation/'],
            ],
        ],
        // Mixed assembly + QC execution surface: leave untagged until the runtime
        // has a justified multi-token contract instead of forcing a fake single lane.
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'processing_operation',
            'feature_key' => 'processing_operation',
            'label_key' => 'nav.processing_operation',
            'label' => 'Processing Operation',
            'url' => '/apps/manufacturing/processing-operation',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 45,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/processing-operation'],
                'prefix' => ['/apps/manufacturing/processing-operation/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'production_workboard',
            'feature_key' => 'production_workboard',
            'module_token' => 'production',
            'label_key' => 'nav.production_workboard',
            'label' => 'Production Workboard',
            'url' => '/apps/manufacturing/production-workboard',
            'visible_if' => 'role_machine_leader',
            'nav_visible' => true,
            'order' => 30,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/production-workboard', '/manufacturing/production-workboard', '/machines/leader'],
                'prefix' => ['/apps/manufacturing/production-workboard/', '/manufacturing/production-workboard/', '/machines/leader/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'assembly_dashboard',
            'feature_key' => 'assembly_dashboard',
            'module_token' => 'assembly',
            'label_key' => 'nav.assembly_leader',
            'label' => 'Assembly Dashboard',
            'url' => '/apps/manufacturing/assembly-dashboard',
            'visible_if' => 'role_assembly_leader',
            'nav_visible' => true,
            'order' => 40,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/assembly-dashboard'],
                'prefix' => ['/apps/manufacturing/assembly-dashboard/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'qc_dashboard',
            'feature_key' => 'qc_dashboard',
            'module_token' => 'qc',
            'label_key' => 'nav.qc_leader',
            'label' => 'QC Workspace',
            'url' => '/apps/manufacturing/qc-dashboard',
            'menu_key' => 'ipm.qc_leader',
            'visible_if' => 'role_qc_leader',
            'nav_visible' => true,
            'order' => 50,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/qc-dashboard'],
                'prefix' => ['/apps/manufacturing/qc-dashboard/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'qc_workboard',
            'feature_key' => 'qc_workboard',
            'module_token' => 'qc',
            'label_key' => 'nav.qc_workboard',
            'label' => 'QC Workboard',
            'url' => '/apps/manufacturing/qc-workboard',
            'visible_if' => 'role_qc_leader',
            'nav_visible' => true,
            'order' => 60,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/qc-workboard', '/manufacturing/qc-workboard', '/qc-entries/leader'],
                'prefix' => ['/apps/manufacturing/qc-workboard/', '/manufacturing/qc-workboard/', '/qc-entries/leader/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'dispatch_dashboard',
            'feature_key' => 'dispatch_dashboard',
            'module_token' => 'dispatch',
            'label_key' => 'nav.dispatch_leader',
            'label' => 'Dispatch Workspace',
            'url' => '/apps/manufacturing/dispatch-dashboard',
            'menu_key' => 'ipm.dispatch_leader',
            'visible_if' => 'role_dispatch_leader',
            'nav_visible' => true,
            'order' => 70,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/dispatch-dashboard'],
                'prefix' => ['/apps/manufacturing/dispatch-dashboard/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'dispatch_workboard',
            'feature_key' => 'dispatch_ops',
            'module_token' => 'dispatch',
            'label_key' => 'nav.dispatch_ops',
            'label' => 'Dispatch Ops',
            'url' => '/apps/manufacturing/dispatch-ops',
            'visible_if' => 'role_ops_or_dispatch_leader',
            'order' => 80,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/dispatch-ops', '/manufacturing/dispatch-ops', '/apps/manufacturing/dispatch-workboard', '/manufacturing/dispatch-workboard', '/dispatch-entries/leader'],
                'prefix' => ['/apps/manufacturing/dispatch-ops/', '/manufacturing/dispatch-ops/', '/apps/manufacturing/dispatch-workboard/', '/manufacturing/dispatch-workboard/', '/dispatch-entries/leader/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.workboards',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'stage_board',
            'module_token' => 'production',
            'label_key' => 'nav.stage_board',
            'url' => '/apps/manufacturing/stage-board',
            'route_fallback_file' => 'plugins/Base/routes.php',
            'visible_if' => 'logged_in',
            'order' => 90,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/stage-board', '/manufacturing/stage-board'],
                'prefix' => ['/apps/manufacturing/stage-board/', '/manufacturing/stage-board/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.demand_orders',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'demand_dashboard',
            'feature_key' => 'demand_dashboard',
            'module_token' => 'demands',
            'label_key' => 'nav.demand_dashboard',
            'label' => 'Demand Workspace',
            'url' => '/apps/manufacturing/demand-dashboard',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 10,
            'priority' => 88,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/demand-dashboard', '/manufacturing/demand-dashboard'],
                'prefix' => ['/apps/manufacturing/demand-dashboard/', '/manufacturing/demand-dashboard/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.demand_orders',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'daily_orders',
            'feature_key' => 'daily_orders',
            'module_token' => 'production',
            'label_key' => 'nav.daily_orders',
            'label' => 'Daily Orders',
            'url' => '/apps/manufacturing/daily-orders',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 20,
            'priority' => 84,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/daily-orders', '/daily-orders'],
                'prefix' => ['/apps/manufacturing/daily-orders/', '/daily-orders/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.demand_orders',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'coverage_dashboard',
            'module_token' => 'coverage',
            'label_key' => 'nav.coverage_dashboard',
            'url' => '/apps/manufacturing/coverage',
            'visible_if' => 'role_ops',
            'order' => 30,
            'priority' => 82,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/coverage', '/manufacturing/coverage'],
                'prefix' => ['/apps/manufacturing/coverage/', '/manufacturing/coverage/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.demand_orders',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'production_plans',
            'feature_key' => 'production_plans',
            'module_token' => 'production',
            'label_key' => 'nav.production_plans',
            'label' => 'Production Plans',
            'url' => '/apps/manufacturing/production-plans',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 40,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/production-plans', '/production-plans'],
                'prefix' => ['/apps/manufacturing/production-plans/', '/production-plans/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.demand_orders',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'demand_engine',
            'feature_key' => 'demand_workspace',
            'module_token' => 'demands',
            'label' => 'Demand Workspace',
            'label_key' => 'nav.demand_workspace',
            'url' => '/apps/manufacturing/demands',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 50,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/demands', '/manufacturing/demands'],
                'prefix' => ['/apps/manufacturing/demands/', '/manufacturing/demands/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.demand_orders',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'order_processing_prep',
            'feature_key' => 'order_processing_prep',
            'module_token' => 'dispatch',
            'label_key' => 'nav.order_processing_prep',
            'label' => 'Order Preparation',
            'url' => '/apps/manufacturing/dispatch-ops/preparation',
            'visible_if' => 'role_ops',
            'order' => 55,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/dispatch-ops/preparation', '/manufacturing/dispatch-ops/preparation'],
                'prefix' => ['/apps/manufacturing/dispatch-ops/preparation/', '/manufacturing/dispatch-ops/preparation/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.materials_supply',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'material_dashboard',
            'feature_key' => 'material_management',
            'module_token' => 'materials',
            'label_key' => 'nav.material_dashboard',
            'label' => 'Materials Workspace',
            'url' => '/apps/manufacturing/materials',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 56,
            'priority' => 86,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/materials'],
                'prefix' => ['/apps/manufacturing/materials/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.materials_supply',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'material_stock',
            'feature_key' => 'material_stock',
            'module_token' => 'materials',
            'label_key' => 'nav.material_stock',
            'label' => 'Material Stock',
            'url' => '/apps/manufacturing/materials/stock',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 57,
            'priority' => 85,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/materials/stock'],
                'prefix' => ['/apps/manufacturing/materials/stock/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.materials_supply',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'material_orders',
            'feature_key' => 'material_orders',
            'module_token' => 'materials',
            'label_key' => 'nav.material_orders',
            'label' => 'Material Orders',
            'url' => '/apps/manufacturing/materials/orders',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 58,
            'priority' => 84,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/materials/orders'],
                'prefix' => ['/apps/manufacturing/materials/orders/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.materials_supply',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'material_receipt',
            'feature_key' => 'material_receipt',
            'module_token' => 'materials',
            'label_key' => 'nav.material_receipt',
            'label' => 'Material Receipt',
            'url' => '/apps/manufacturing/materials/receipt',
            'visible_if' => 'role_ops',
            'nav_visible' => true,
            'order' => 59,
            'priority' => 83,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/materials/receipt'],
                'prefix' => ['/apps/manufacturing/materials/receipt/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.queues',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'production_queue',
            'feature_key' => 'production_queue',
            'module_token' => 'production',
            'label_key' => 'nav.production_queue',
            'label' => 'Production Queue',
            'url' => '/apps/manufacturing/production-queue',
            'visible_if' => 'role_machine_leader',
            'nav_visible' => true,
            'order' => 10,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/production-queue', '/manufacturing/production-queue', '/production-queue'],
                'prefix' => ['/apps/manufacturing/production-queue/', '/manufacturing/production-queue/', '/production-queue/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.queues',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'assembly_queue',
            'feature_key' => 'assembly_queue',
            'module_token' => 'assembly',
            'label_key' => 'nav.assembly_queue',
            'label' => 'Assembly Queue',
            'url' => '/apps/manufacturing/assembly-queue',
            'visible_if' => 'role_assembly_leader',
            'nav_visible' => true,
            'order' => 20,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/assembly-queue', '/manufacturing/assembly-queue', '/manufacturing/assembly-demand-queue'],
                'prefix' => ['/apps/manufacturing/assembly-queue/', '/manufacturing/assembly-queue/', '/manufacturing/assembly-demand-queue/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.queues',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'qc_queue',
            'feature_key' => 'qc_queue',
            'module_token' => 'qc',
            'label_key' => 'nav.qc_queue',
            'label' => 'QC Queue',
            'url' => '/apps/manufacturing/qc-queue',
            'runtime_fallback_urls' => ['/apps/manufacturing/qc-workboard', '/manufacturing/qc-workboard', '/qc-entries/leader'],
            'visible_if' => 'role_qc_leader',
            'nav_visible' => true,
            'order' => 30,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/qc-queue', '/manufacturing/qc-queue', '/manufacturing/qc-demand-queue'],
                'prefix' => ['/apps/manufacturing/qc-queue/', '/manufacturing/qc-queue/', '/manufacturing/qc-demand-queue/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.reference',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'parts_master',
            'module_token' => 'demands',
            'label_key' => 'nav.parts_master',
            'url' => '/apps/manufacturing/products',
            'menu_key' => 'ipm.products',
            'visible_if' => 'role_ops',
            'order' => 5,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/products', '/products'],
                'prefix' => ['/apps/manufacturing/products/', '/products/'],
            ],
        ],
        [
            'source_key' => 'apps.manufacturing.reference',
            'group' => 'Apps',
            'section' => 'Manufacturing',
            'module' => 'manufacturing_ipm',
            'owner' => 'manufacturing',
            'key' => 'assembly_plans',
            'feature_key' => 'assembly_plans',
            'module_token' => 'assembly',
            'label_key' => 'nav.assembly_plans',
            'label' => 'Assembly Plans',
            'url' => '/apps/manufacturing/assembly-plans',
            'visible_if' => 'role_assembly_leader',
            'nav_visible' => true,
            'order' => 20,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/apps/manufacturing/assembly-plans', '/manufacturing/assembly-plans'],
                'prefix' => ['/apps/manufacturing/assembly-plans/', '/manufacturing/assembly-plans/'],
            ],
        ],
    ],
];
