<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-open.php'; ?>
<div class="card"><div class="row u-style-2d7d2729a4"><h2 class="u-style-1169661891"><?= e(t('module.qc_entries.add')) ?></h2><a class="btn" href="/qc-entries"><?= e(t('common.back_to_list')) ?></a></div></div>
<?php if (!empty($error ?? '')): ?><div class="card u-style-64e7e2c551"><?= e((string)$error) ?></div><?php endif; ?>
<div class="card"><form method="post" action="/qc-entries/add" class="row"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>">
<div class="u-style-c4bb1f9ef6"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.qc_plan_optional')) ?></label><select name="qc_plan_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($qc_plans as $q): ?><option value="<?= (int)$q['id'] ?>" <?= ((int)($old['qc_plan_id'] ?? 0) === (int)$q['id']) ? 'selected' : '' ?>>#<?= (int)$q['id'] ?> <?= e((string)$q['plan_date']) ?> (<?= e((string)$q['planned_qty']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-c4bb1f9ef6"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.daily_order_optional')) ?></label><select name="daily_order_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($daily_orders as $d): ?><option value="<?= (int)$d['id'] ?>" <?= ((int)($old['daily_order_id'] ?? 0) === (int)$d['id']) ? 'selected' : '' ?>>#<?= (int)$d['id'] ?> <?= e((string)$d['customer_name']) ?> (<?= e((string)$d['order_date']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-c4bb1f9ef6"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.production_plan_optional')) ?></label><select name="production_plan_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($production_plans as $pp): ?><option value="<?= (int)$pp['id'] ?>" <?= ((int)($old['production_plan_id'] ?? 0) === (int)$pp['id']) ? 'selected' : '' ?>>#<?= (int)$pp['id'] ?> <?= e((string)$pp['plan_date']) ?> (<?= e((string)$pp['planned_qty']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-b9403873cd"><label class="muted u-style-98847c28df"><?= e(t('common.part')) ?> *</label><select name="product_id" required><option value=""><?= e(t('module.part_machine_map.select_part')) ?></option><?php foreach ($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= ((int)($old['product_id'] ?? 0) === (int)$p['id']) ? 'selected' : '' ?>><?= e((string)$p['parts_name']) ?> (<?= e((string)$p['parts_number']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.qc_type')) ?></label><input class="input" name="qc_type" value="<?= e((string)($old['qc_type'] ?? 'Final')) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.checked_qty')) ?> *</label><input class="input" type="number" step="0.01" name="checked_qty" required value="<?= e((string)($old['checked_qty'] ?? '')) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.pass_qty')) ?></label><input class="input" type="number" step="0.01" name="pass_qty" value="<?= e((string)($old['pass_qty'] ?? '0')) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.fail_qty')) ?></label><input class="input" type="number" step="0.01" name="fail_qty" value="<?= e((string)($old['fail_qty'] ?? '0')) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('common.status')) ?></label><input class="input" name="status" value="<?= e((string)($old['status'] ?? 'Open')) ?>"></div>
<div class="u-style-4ca11fcb42"><label class="muted u-style-98847c28df"><?= e(t('common.remarks')) ?></label><textarea name="remarks"><?= e((string)($old['remarks'] ?? '')) ?></textarea></div>
<div class="row u-style-0466783d98"><button class="btn ok" type="submit"><?= e(t('module.qc_entries.save')) ?></button><a class="btn" href="/qc-entries"><?= e(t('common.cancel')) ?></a></div>
</form></div>
<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-close.php'; ?>
