<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-open.php'; ?>
<?php
$gov = is_array($governance ?? null) ? $governance : [];
$approvalEvents = is_array($approval_events ?? null) ? $approval_events : [];
$activityTimeline = is_array($activity_timeline ?? null) ? $activity_timeline : [];
$isLocked = !empty($gov['locked']);
$approvalLabel = static function (string $status): string {
    return match (strtolower(trim($status))) {
        'pending approval' => t('ops.approval_inbox.status_pending_approval'),
        'approved' => t('ops.approval_inbox.status_approved'),
        'rejected' => t('ops.approval_inbox.status_rejected'),
        'reopened' => t('ops.approval_inbox.status_reopened'),
        'draft' => t('ops.approval_inbox.status_draft'),
        default => $status,
    };
};
$isAdmin = function_exists('base_is_admin_user') ? base_is_admin_user() : false;
?>
<div class="card"><div class="row u-style-2d7d2729a4"><h2 class="u-style-1169661891"><?= e(t('common.edit')) ?> <?= e(t('module.qc_entries.title')) ?> #<?= (int)$row['id'] ?></h2><div class="row u-style-f0abc1db33"><a class="btn" href="/qc-entries"><?= e(t('common.back_to_list')) ?></a><?php if ($isAdmin): ?><a class="btn" style="background: var(--style-subtle-bg);color: var(--text);border-color: var(--style-border-soft);" href="/admin/system-tools/stage-inspector?inspect_entity=QCEntry&inspect_id=<?= (int)$row['id'] ?>" target="_blank" title="Stage Inspector (Admin)">Stage Inspector</a><?php endif; ?></div></div></div>
<?php if (!empty($error ?? '')): ?><div class="card u-style-64e7e2c551"><?= e((string)$error) ?></div><?php endif; ?>
<?php $ownership_title = 'Operational Ownership'; require APP_ROOT . '/public/views/partials/ownership_summary.php'; ?>
<div class="card">
	<div class="row u-style-91ebbdc206">
		<div class="ui-block"><strong><?= e(t('ops.approval_inbox.approval')) ?>:</strong> <?= e($approvalLabel((string)($row['approval_status'] ?? 'draft'))) ?> | <strong><?= e(t('ops.approval_inbox.lock')) ?>:</strong> <?= $isLocked ? e(t('ops.approval_inbox.locked_badge')) : e(t('ops.approval_inbox.unlocked_badge')) ?></div>
		<div class="muted"><?= e(t('ops.qc_dispatch_edit.approved_by_at')) ?> <?= e((string)($row['approved_by'] ?? '-')) ?> <?= e(t('ops.supervisor_cockpit.at')) ?> <?= e((string)($row['approved_at'] ?? '-')) ?></div>
	</div>
	<?php if ($isLocked): ?><div class="card u-style-f47b09d788"><?= e(t('ops.qc_dispatch_edit.locked_help_qc')) ?></div><?php endif; ?>
	<div class="row u-style-8bb0cda49c">
		<?php if (!empty($gov['can_submit'])): ?><form class="u-style-ed6103acbe" method="post" action="/qc-entries/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="submit"><input class="input" name="note" placeholder="<?= e(t('ops.dispatch_leader.submit_for_approval')) ?>"><button class="btn" type="submit"><?= e(t('ops.dispatch_leader.submit_for_approval')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_approve'])): ?><form class="u-style-ed6103acbe" method="post" action="/qc-entries/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="approve"><input class="input" name="note" placeholder="<?= e(t('ops.dispatch_leader.approval_note')) ?>"><button class="btn ok" type="submit"><?= e(t('ops.approval_inbox.action_approve')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_reject'])): ?><form class="u-style-ed6103acbe" method="post" action="/qc-entries/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="reject"><input class="input" name="reason" placeholder="<?= e(t('ops.qc_dispatch_edit.reject_reason')) ?>" required><input class="input" name="note" placeholder="<?= e(t('ops.qc_dispatch_edit.optional_note')) ?>"><button class="btn" type="submit"><?= e(t('ops.approval_inbox.action_reject')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_reopen'])): ?><form class="u-style-ed6103acbe" method="post" action="/qc-entries/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="reopen"><input class="input" name="reason" placeholder="<?= e(t('ops.qc_dispatch_edit.reopen_reason')) ?>" required><input class="input" name="note" placeholder="<?= e(t('ops.qc_dispatch_edit.optional_note')) ?>"><button class="btn" type="submit"><?= e(t('ops.approval_inbox.action_reopen')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_override'])): ?><form class="u-style-ed6103acbe" method="post" action="/qc-entries/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="unlock_override"><input class="input" name="reason" placeholder="<?= e(t('ops.qc_dispatch_edit.override_reason')) ?>" required><button class="btn" type="submit"><?= e(t('ops.approval_inbox.action_unlock_override')) ?></button></form><?php endif; ?>
	</div>
<form method="post" action="/qc-entries/edit" class="row"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><fieldset <?= $isLocked ? 'disabled' : '' ?> style="border:0;padding:0;margin:0;display:contents">
<div class="u-style-c4bb1f9ef6"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.qc_plan_optional')) ?></label><select name="qc_plan_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($qc_plans as $q): ?><option value="<?= (int)$q['id'] ?>" <?= ((int)($row['qc_plan_id'] ?? 0) === (int)$q['id']) ? 'selected' : '' ?>>#<?= (int)$q['id'] ?> <?= e((string)$q['plan_date']) ?> (<?= e((string)$q['planned_qty']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-c4bb1f9ef6"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.daily_order_optional')) ?></label><select name="daily_order_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($daily_orders as $d): ?><option value="<?= (int)$d['id'] ?>" <?= ((int)($row['daily_order_id'] ?? 0) === (int)$d['id']) ? 'selected' : '' ?>>#<?= (int)$d['id'] ?> <?= e((string)$d['customer_name']) ?> (<?= e((string)$d['order_date']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-c4bb1f9ef6"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.production_plan_optional')) ?></label><select name="production_plan_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($production_plans as $pp): ?><option value="<?= (int)$pp['id'] ?>" <?= ((int)($row['production_plan_id'] ?? 0) === (int)$pp['id']) ? 'selected' : '' ?>>#<?= (int)$pp['id'] ?> <?= e((string)$pp['plan_date']) ?> (<?= e((string)$pp['planned_qty']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-b9403873cd"><label class="muted u-style-98847c28df"><?= e(t('common.part')) ?> *</label><select name="product_id" required><?php foreach ($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= ((int)$row['product_id'] === (int)$p['id']) ? 'selected' : '' ?>><?= e((string)$p['parts_name']) ?> (<?= e((string)$p['parts_number']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.qc_type')) ?></label><input class="input" name="qc_type" value="<?= e((string)$row['qc_type']) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.checked_qty')) ?> *</label><input class="input" type="number" step="0.01" name="checked_qty" required value="<?= e((string)$row['checked_qty']) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.pass_qty')) ?></label><input class="input" type="number" step="0.01" name="pass_qty" value="<?= e((string)$row['pass_qty']) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.qc_entries.fail_qty')) ?></label><input class="input" type="number" step="0.01" name="fail_qty" value="<?= e((string)$row['fail_qty']) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('common.status')) ?></label><input class="input" name="status" value="<?= e((string)$row['status']) ?>"></div>
<div class="u-style-4ca11fcb42"><label class="muted u-style-98847c28df"><?= e(t('common.remarks')) ?></label><textarea name="remarks"><?= e((string)($row['remarks'] ?? '')) ?></textarea></div>
<div class="row u-style-0466783d98"><button class="btn ok" type="submit"><?= e(t('module.qc_entries.update')) ?></button><a class="btn" href="/qc-entries"><?= e(t('common.cancel')) ?></a></div>
</fieldset></form></div>
<?php if (!empty($approvalEvents)): ?><div class="card"><h3 class="u-style-d462248a40"><?= e(t('ops.qc_dispatch_edit.governance_history')) ?></h3><div class="table-wrap"><table><thead><tr><th><?= e(t('ops.approval_inbox.when')) ?></th><th><?= e(t('ops.approval_inbox.action')) ?></th><th><?= e(t('ops.approval_inbox.approval')) ?></th><th><?= e(t('ops.approval_inbox.lock')) ?></th><th><?= e(t('ops.approval_inbox.reason_note')) ?></th><th><?= e(t('ops.approval_inbox.note_prefix')) ?></th><th><?= e(t('ops.approval_inbox.actor')) ?></th></tr></thead><tbody><?php foreach ($approvalEvents as $event): ?><tr><td><?= e((string)($event['acted_at'] ?? '')) ?></td><td><?= e((string)($event['action_name'] ?? '')) ?></td><td><?= e($approvalLabel((string)($event['previous_approval_status'] ?? '-'))) ?> -> <?= e($approvalLabel((string)($event['new_approval_status'] ?? '-'))) ?></td><td><?= (((int)($event['previous_locked_state'] ?? 0) === 1) ? e(t('ops.approval_inbox.locked_badge')) : e(t('ops.approval_inbox.unlocked_badge'))) ?> -> <?= (((int)($event['new_locked_state'] ?? 0) === 1) ? e(t('ops.approval_inbox.locked_badge')) : e(t('ops.approval_inbox.unlocked_badge'))) ?></td><td><?= e((string)($event['reason_text'] ?? '')) ?></td><td><?= e((string)($event['note_text'] ?? '')) ?></td><td><?= e((string)($event['actor_email'] ?? t('common.system'))) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<?php if (!empty($activityTimeline)): ?><div class="card"><h3 class="u-style-d462248a40">Activity Timeline</h3><div class="table-wrap"><table><thead><tr><th><?= e(t('ops.approval_inbox.when')) ?></th><th><?= e(t('ops.approval_inbox.action')) ?></th><th>Type</th><th>State</th><th><?= e(t('ops.approval_inbox.reason_note')) ?></th><th>Changes</th><th><?= e(t('ops.approval_inbox.actor')) ?></th></tr></thead><tbody><?php foreach ($activityTimeline as $event): ?><tr><td><?= e((string)($event['created_at'] ?? '')) ?></td><td><?= e((string)($event['action_name'] ?? '')) ?></td><td><?= e((string)($event['event_type'] ?? '')) ?></td><td><?= e((string)($event['old_state'] ?? '-')) ?> -> <?= e((string)($event['new_state'] ?? '-')) ?></td><td><?= e(trim((string)($event['reason_text'] ?? '')) !== '' ? (string)$event['reason_text'] : (string)($event['note_text'] ?? '')) ?></td><td><?php $diff = is_array($event['diff'] ?? null) ? $event['diff'] : []; ?><?php if (!empty($diff)): ?><?php $items = []; foreach ($diff as $d) { $items[] = (string)($d['field'] ?? '') . ': ' . (string)($d['old'] ?? '-') . ' -> ' . (string)($d['new'] ?? '-'); } ?><?= e(implode(' | ', $items)) ?><?php else: ?>-<?php endif; ?></td><td><?= e((string)($event['actor_label'] ?? t('common.system'))) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-close.php'; ?>
