<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'shell',
    'items' => [
        [
            'source_key' => 'shell.entry.home',
            'group' => 'Operations',
            'section' => 'Home',
            'module' => 'platform',
            'owner' => 'shell',
            'key' => 'shell_home_entry',
            'feature_key' => 'shell_home',
            'module_token' => 'ops',
            'label_key' => 'nav.my_work',
            'url' => '/',
            'visible_if' => 'role_ops',
            'nav_visible' => false,
            'order' => 10,
            'priority' => 100,
            'always_visible' => true,
            'style' => ['is_dashboard' => true],
            'active_patterns' => [
                'exact' => ['/'],
                'prefix' => [],
            ],
        ],
        [
            'source_key' => 'core.operations.review',
            'group' => 'Operations',
            'section' => 'Approve / Review',
            'module' => 'platform',
            'owner' => 'shell',
            'key' => 'approval_inbox',
            'module_token' => 'ops',
            'label_key' => 'nav.approval_inbox',
            'url' => '/ops/approval-inbox',
            'visible_if' => 'role_governance',
            'order' => 10,
            'priority' => 90,
            'style' => ['is_action' => true],
            'active_patterns' => [
                'exact' => ['/ops/approval-inbox'],
                'prefix' => ['/ops/approval-inbox/'],
            ],
        ],
        [
            'source_key' => 'core.operations.review',
            'group' => 'Operations',
            'section' => 'Approve / Review',
            'module' => 'platform',
            'owner' => 'shell',
            'key' => 'alerts',
            'module_token' => 'ops',
            'label_key' => 'nav.notifications',
            'url' => '/ops/notifications',
            'menu_key' => 'apps.notifications',
            'visible_if' => 'logged_in',
            'order' => 20,
            'style' => ['is_secondary' => true],
            'active_patterns' => [
                'exact' => ['/ops/notifications'],
                'prefix' => ['/ops/notifications/'],
            ],
        ],
    ],
];
