<?php
return [
    'key' => 'package_tool',
    'name' => 'Package Tool',
    'name_key' => 'studio.tool.package_tool.name',
    'description_key' => 'studio.tool.package_tool.description',
    'category' => 'lifecycle',
    'home_group' => 'architecture',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/package-tool',
    'placeholder' => true,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging'],
    'routes' => ['/apps/studio/tools/package-tool'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['package', 'app', 'module'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
