<?php
return [
    'key' => 'nav_menu_tool',
    'name' => 'Nav Menu Tool',
    'name_key' => 'studio.tool.nav_menu_tool.name',
    'description_key' => 'studio.tool.nav_menu_tool.description',
    'category' => 'authoring',
    'home_group' => 'composition',
    'status' => 'read_only',
    'canonical_route' => '/apps/studio/tools/nav-composer',
    'placeholder' => false,
    'risk_level' => 'medium',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/nav-composer'],
    'views' => ['apps/Studio/Views/gui_studio_nav_composer.php'],
    'services' => ['Apps\\Studio\\Services\\StudioNavLinkingService'],
    'owner' => 'studio',
    'migration' => [
        'status' => 'bridge_active',
        'from' => 'menu_editor',
        'note' => 'Legacy Menu Editor entry remains as a compatibility surface while the governed nav composer is canonical.',
    ],
    'can_load' => ['nav', 'route', 'app', 'module'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => true,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
