<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'platform',
    'items' => [
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'admin_upgrade_catalog',
            'module_token' => 'admin',
            'label_key' => 'admin.upgrade_catalog.title',
            'url' => '/admin/system-tools/upgrade-catalog',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 79,
            'priority' => 48,
            'style' => ['is_secondary' => true],
            'section' => 'Developer',
            'active_patterns' => ['exact' => ['/admin/system-tools/upgrade-catalog'], 'prefix' => []],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'platform_operations',
            'module_token' => 'admin',
            'label_key' => 'ops.platform_operations.title',
            'url' => '/ops/platform-operations',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 5,
            'priority' => 101,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/platform-operations'],
                'prefix' => [],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'access_control_board',
            'module_token' => 'admin',
            'label_key' => 'nav.access_control_board',
            'label' => 'Access Control Board',
            'url' => '/ops/access-control',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 20,
            'priority' => 96,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/access-control', '/ops/dashboard-assignments'],
                'prefix' => ['/ops/access-control/', '/ops/dashboard-assignments/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'user_control_board',
            'module_token' => 'admin',
            'label_key' => 'nav.user_control_board',
            'label' => 'User Control Board',
            'url' => '/ops/user-control',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 23,
            'priority' => 94,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/user-control'],
                'prefix' => ['/ops/user-control/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'display_manager',
            'module_token' => 'admin',
            'label_key' => 'ops.platform_admin_tools.link.display_manager',
            'url' => '/ops/display-manager',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 24,
            'priority' => 93,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/display-manager'],
                'prefix' => ['/ops/display-manager/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'operator_tasks',
            'module_token' => 'admin',
            'label_key' => 'nav.operator_tasks',
            'url' => '/ops/operator-tasks',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 25,
            'priority' => 92,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/operator-tasks'],
                'prefix' => ['/ops/operator-tasks/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'workspace_profiles',
            'module_token' => 'admin',
            'label_key' => 'nav.workspace_profiles',
            'url' => '/ops/workspace-profiles',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 28,
            'priority' => 88,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/workspace-profiles'],
                'prefix' => ['/ops/workspace-profiles/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'audit_explorer',
            'module_token' => 'admin',
            'label_key' => 'nav.audit_explorer',
            'label' => 'Audit Explorer',
            'url' => '/ops/audit-log',
            'visible_if' => 'ops_audit_explorer',
            'order' => 30,
            'priority' => 55,
            'style' => ['is_secondary' => true],
            'section' => 'Governance',
            'active_patterns' => [
                'exact' => ['/ops/audit-log'],
                'prefix' => ['/ops/audit-log/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'apps_management',
            'module_token' => 'admin',
            'label_key' => 'nav.apps_management',
            'label' => 'Apps Management',
            'url' => '/admin/apps',
            'menu_key' => 'admin.apps',
            'visible_if' => 'admin_tools',
            'order' => 40,
            'priority' => 88,
            'always_visible' => true,
            'style' => ['is_secondary' => true],
            'section' => 'Apps & Config',
            'active_patterns' => [
                'exact' => ['/admin/apps'],
                'prefix' => ['/admin/apps/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'route_registry',
            'module_token' => 'admin',
            'label_key' => 'nav.route_registry',
            'label' => 'Route Registry',
            'url' => '/admin/routes',
            'menu_key' => 'admin.routes',
            'visible_if' => 'admin_tools',
            'order' => 50,
            'priority' => 62,
            'style' => ['is_secondary' => true],
            'section' => 'Developer',
            'active_patterns' => [
                'exact' => ['/admin/routes'],
                'prefix' => ['/admin/routes/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'platform_settings_builder',
            'module_token' => 'admin',
            'label_key' => 'common.base',
            'url' => '/admin/base',
            'menu_key' => 'admin.base_builder',
            'visible_if' => 'can_access_base',
            'order' => 60,
            'priority' => 52,
            'style' => ['is_secondary' => true],
            'section' => 'Apps & Config',
            'engineering_workspace' => [
                'surface_classification' => 'workspace_root',
                'workspace_key' => 'Plugin/Base',
            ],
            'active_patterns' => [
                'exact' => ['/admin/base'],
                'prefix' => ['/admin/base/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'system_tools',
            'module_token' => 'admin',
            'label_key' => 'nav.system_tools',
            'label' => 'System Tools',
            'url' => '/admin/system-tools',
            'visible_if' => 'admin_tools',
            'order' => 70,
            'priority' => 50,
            'style' => ['is_secondary' => true],
            'section' => 'System Tools',
            'active_patterns' => [
                'exact' => ['/admin/system-tools'],
                'prefix' => ['/admin/system-tools/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'platform_setup',
            'module_token' => 'admin',
            'label_key' => 'ops.platform_admin_tools.link.setup',
            'url' => '/admin/setup',
            'visible_if' => 'admin_tools',
            'order' => 75,
            'priority' => 49,
            'style' => ['is_secondary' => true],
            'section' => 'System Tools',
            'active_patterns' => [
                'exact' => ['/admin/setup'],
                'prefix' => ['/admin/setup/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'platform_mode',
            'module_token' => 'admin',
            'label_key' => 'admin.platform_mode.title',
            'url' => '/admin/system-tools/platform-mode',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 77,
            'priority' => 49,
            'style' => ['is_secondary' => true],
            'section' => 'System Tools',
            'active_patterns' => [
                'exact' => ['/admin/system-tools/platform-mode'],
                'prefix' => [],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'architecture_health',
            'module_token' => 'developer_tools',
            'label_key' => 'nav.architecture_health',
            'url' => '/admin/architecture-health',
            'visible_if' => 'developer_tools',
            'order' => 80,
            'priority' => 48,
            'style' => ['is_secondary' => true],
            'section' => 'Developer',
            'active_patterns' => [
                'exact' => ['/admin/architecture-health'],
                'prefix' => ['/admin/architecture-health/'],
            ],
        ],
        [
            'source_key' => 'admin.platform.system',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'widget_builder',
            'module_token' => 'developer_tools',
            'label_key' => 'ops.platform_operations.card.widget_builder',
            'url' => '/ops/widget-builder',
            'visible_if' => 'developer_tools',
            'order' => 82,
            'priority' => 46,
            'style' => ['is_secondary' => true],
            'section' => 'Developer',
            'active_patterns' => ['exact' => ['/ops/widget-builder'], 'prefix' => ['/ops/widget-builder/']],
        ],
        // Platform internal compatibility routes (hidden from sidebar)
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_access_control_detail',
            'url' => '/ops/access-control/detail',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 801,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_access_control_save',
            'url' => '/ops/access-control/save',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 802,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_dashboard_assignments',
            'url' => '/ops/dashboard-assignments',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 803,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_dashboard_assignments_detail',
            'url' => '/ops/dashboard-assignments/detail',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 804,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_dashboard_assignments_save',
            'url' => '/ops/dashboard-assignments/save',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 805,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_user_control_detail',
            'url' => '/ops/user-control/detail',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 806,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_user_control_save',
            'url' => '/ops/user-control/save',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 807,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_display_manager_save',
            'url' => '/ops/display-manager/save',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 808,
            'nav_visible' => false,
        ],
        [
            'source_key' => 'admin.platform.internal',
            'group' => 'Admin',
            'module' => 'platform',
            'owner' => 'platform',
            'key' => 'ops_audit_log_entity_detail',
            'url' => '/ops/audit-log/entity-detail',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'order' => 809,
            'nav_visible' => false,
        ],
    ],
];
