<?php
return [
    'key' => 'helper_tool',
    'name' => 'Repository Scanner',
    'name_key' => 'studio.tool.helper_tool.name',
    'description_key' => 'studio.tool.helper_tool.description',
    'category' => 'discovery',
    'home_group' => 'governance',
    'status' => 'available',
    'canonical_route' => '/apps/studio/tools/helper-tool',
    'placeholder' => false,
    'risk_level' => 'read_only',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/helper-tool'],
    'views' => ['apps/Studio/Tools/HelperTool/Views/preview.php'],
    'services' => [
        'Apps\Studio\Services\StudioOwnerDiscoveryService',
        'Apps\Studio\Tools\HelperTool\Services\RepoTreeScannerService',
    ],
    'owner' => 'studio',
    'can_load' => ['app', 'module', 'view', 'dashboard', 'route', 'nav'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => false,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
