<?php
return [
    'tool_key' => 'form_builder',
    'key' => 'form_builder',
    'label' => 'Form Builder',
    'name' => 'Form Builder',
    'name_key' => 'studio.tool.form_builder.name',
    'description_key' => 'studio.tool.form_builder.description',
    'category' => 'authoring',
    'home_group' => 'composition',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/form-builder',
    'placeholder' => true,
    'risk_level' => 'medium',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/form-builder'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['form', 'view', 'component', 'schema'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
