<?php
return [
    'key' => 'owner_structure_scan',
    'name' => 'Owner Structure Scan',
    'name_key' => 'studio.tool.owner_structure_scan.name',
    'description_key' => 'studio.tool.owner_structure_scan.description',
    'category' => 'governance',
    'home_group' => 'governance',
    'status' => 'available',
    'canonical_route' => '/apps/studio/tools/owner-structure-scan',
    'placeholder' => false,
    'risk_level' => 'guarded_initialization',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/owner-structure-scan',
        '/apps/studio/tools/owner-structure-scan/initialize-workspace-artifacts',
        '/apps/studio/tools/owner-structure-scan/deletion-approval-record',
        '/apps/studio/tools/owner-structure-scan/deletion-execution-request',
        '/apps/studio/tools/owner-structure-scan/deletion-execution-claim',
        '/apps/studio/tools/owner-structure-scan/deletion-snapshot-create',
    ],
    'views' => [
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.deletion-plan.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zz-deletion-change-set.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzz-deletion-approval.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzz-deletion-execution-readiness.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzz-deletion-execution-dry-run.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzz-deletion-execution-request.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzz-deletion-executor-readiness.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzzz-deletion-execution-claim.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzzzz-deletion-snapshot-readiness.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzzzzz-deletion-snapshot-creation.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzzzzzz-deletion-snapshot-integrity.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzzzzzzz-deletion-reference-remediation-readiness.php',
        'apps/Studio/Tools/OwnerStructureScan/Views/preview.postlude.zzzzzzzzzzzzz-deletion-reference-patch-proposal.php',
    ],
    'services' => [
        'Apps\Studio\Services\StudioOwnerDiscoveryService',
        'Apps\Studio\Services\StudioReferenceDiscoveryService',
        'Apps\Studio\Services\StudioDeletionImpactDiscoveryService',
        'Apps\Studio\Services\StudioDeletionPlanService',
        'Apps\Studio\Services\StudioDeletionChangeSetService',
        'Apps\Studio\Services\StudioDeletionApprovalRecordStore',
        'Apps\Studio\Services\StudioDeletionApprovalRecordService',
        'Apps\Studio\Services\StudioDeletionExecutionReadinessService',
        'Apps\Studio\Services\StudioDeletionExecutionDryRunService',
        'Apps\Studio\Services\StudioDeletionExecutionRequestStore',
        'Apps\Studio\Services\StudioDeletionExecutionRequestService',
        'Apps\Studio\Services\StudioDeletionExecutionRequestUseEvidenceStore',
        'Apps\Studio\Services\StudioDeletionExecutorReadinessService',
        'Apps\Studio\Services\StudioDeletionExecutionClaimStore',
        'Apps\Studio\Services\StudioDeletionExecutionClaimService',
        'Apps\Studio\Services\StudioDeletionSnapshotReadinessService',
        'Apps\Studio\Services\StudioDeletionSnapshotStore',
        'Apps\Studio\Services\StudioDeletionSnapshotService',
        'Apps\Studio\Services\StudioDeletionSnapshotIntegrityService',
        'Apps\Studio\Services\StudioDeletionReferenceRemediationReadinessService',
        'Apps\Studio\Services\StudioDeletionReferenceRemediationPatchProposalService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureOwnerDiscoveryService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureFilesystemScannerService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureArtifactClassifierService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureContractV2DiagnosisService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureMigrationPlannerService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureReferenceDiscoveryService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionImpactService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionImpactWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionPlanService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionPlanWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionChangeSetService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionChangeSetWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionApprovalRecordService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionApprovalWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionReadinessService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionReadinessWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionDryRunService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionDryRunWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionRequestService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionRequestWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutorReadinessService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutorReadinessWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionClaimService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionExecutionClaimWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotReadinessService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotReadinessWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotIntegrityService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotIntegrityWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionReferenceRemediationReadinessService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionReferenceRemediationReadinessWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionReferenceRemediationPatchProposalService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionReferenceRemediationPatchProposalWorkspaceService',
        'Apps\Studio\Tools\OwnerStructureScan\Controllers\OwnerStructureDeletionApprovalController',
        'Apps\Studio\Tools\OwnerStructureScan\Controllers\OwnerStructureDeletionExecutionRequestController',
        'Apps\Studio\Tools\OwnerStructureScan\Controllers\OwnerStructureDeletionExecutionClaimController',
        'Apps\Studio\Tools\OwnerStructureScan\Controllers\OwnerStructureDeletionSnapshotController',
        'Apps\Studio\Tools\OwnerStructureScan\Services\EngineeringWorkspaceInitializationService',
        'Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureScanSectionGuardService',
    ],
    'owner' => 'studio',
    'can_load' => ['module'],
    'can_modify' => true,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => false,
];
