<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'studio',
    'items' => [
        [
            'source_key' => 'apps.studio.workspace',
            'group' => 'Admin / System',
            'section' => 'Studio',
            'module' => 'studio',
            'owner' => 'studio',
            'key' => 'studio_workspace',
            'feature_key' => 'studio_workspace',
            'label' => 'OdareHub Studio',
            'url' => '/apps/studio',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'nav_visible' => true,
            'order' => 10,
            'priority' => 100,
            'always_visible' => true,
            'type' => 'system_app',
            'active_patterns' => [
                'exact' => ['/apps/studio'],
                'prefix' => ['/apps/studio/'],
            ],
            'style' => [
                'is_dashboard' => true,
            ],
        ],
        [
            'source_key' => 'apps.studio.workspace',
            'group' => 'Admin / System',
            'section' => 'Studio',
            'module' => 'studio',
            'owner' => 'studio',
            'key' => 'engineering_workspaces_hub',
            'feature_key' => 'studio_engineering_workspaces',
            'label' => 'Engineering Workspaces',
            'url' => '/apps/studio/tools/engineering-workspaces',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'nav_visible' => true,
            'order' => 20,
            'priority' => 90,
            'always_visible' => true,
            'type' => 'tool',
            'engineering_workspace' => [
                'surface_classification' => 'non_workspace',
            ],
            'active_patterns' => [
                'exact' => ['/apps/studio/tools/engineering-workspaces'],
                'prefix' => [],
            ],
        ],
        [
            'source_key' => 'apps.studio.workspace',
            'group' => 'Admin / System',
            'section' => 'Studio',
            'module' => 'studio',
            'owner' => 'studio',
            'key' => 'engineering_workspaces_legacy_viewer',
            'feature_key' => 'studio_engineering_workspaces',
            'label' => 'Engineering Workspaces (Legacy Viewer)',
            'url' => '/apps/studio/engineering-workspaces',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'nav_visible' => false,
            'order' => 1000,
            'priority' => 1,
            'always_visible' => false,
            'type' => 'tool',
            'engineering_workspace' => [
                'surface_classification' => 'non_workspace',
            ],
            'active_patterns' => [
                'exact' => ['/apps/studio/engineering-workspaces'],
                'prefix' => ['/apps/studio/engineering-workspaces/'],
            ],
        ],
        [
            'source_key' => 'apps.studio.workspace',
            'group' => 'Admin / System',
            'section' => 'Studio',
            'module' => 'studio',
            'owner' => 'studio',
            'key' => 'engineering_workspaces_agent_context',
            'feature_key' => 'studio_engineering_workspaces',
            'label' => 'Agent Context',
            'url' => '/apps/studio/tools/engineering-workspaces/agent-context',
            'visible_if' => 'role_platform_admin_or_sysadmin',
            'nav_visible' => false,
            'order' => 1001,
            'priority' => 1,
            'always_visible' => false,
            'type' => 'tool',
            'engineering_workspace' => [
                'surface_classification' => 'non_workspace',
            ],
            'active_patterns' => [
                'exact' => ['/apps/studio/tools/engineering-workspaces/agent-context'],
                'prefix' => [],
            ],
        ],
    ],
];
