<?php
declare(strict_types=1);
$root = dirname(__DIR__, 3);
require_once $root . '/apps/Platform/Services/AdminUpgradeWorkbenchService.php';
use Apps\Platform\Services\AdminUpgradeWorkbenchService;
$checks = 0;
$assert = static function (bool $ok, string $message) use (&$checks): void { $checks++; if (!$ok) { fwrite(STDERR, "FAIL: {$message}\n"); exit(1); } };
$catalog = AdminUpgradeWorkbenchService::catalog();
$inventory = json_decode((string)file_get_contents($root . '/engineering/Shell/admin-dashboard-candidate-inventory.json'), true, 512, JSON_THROW_ON_ERROR);
$assert(count($catalog) === 17, 'catalog contains all 17 active inventory candidates');
$ids = array_column($catalog, 'id');
$assert(count(array_unique($ids)) === 17, 'candidate ids are unique');
$assert(!in_array('ADM-DASH-001', $ids, true), 'deleted Platform Admin dashboard is absent from the active catalog');
$assert(!in_array('ADM-DASH-002', $ids, true), 'deleted App Admin dashboard is absent from the active catalog');
$inventoryStatuses = [];
foreach ((array)($inventory['candidates'] ?? []) as $inventoryCandidate) { $inventoryStatuses[(string)$inventoryCandidate['id']] = (string)$inventoryCandidate['status']; }
$assert(in_array('ADM-MODE-001', $ids, true), 'platform mode candidate exists');
$assert(in_array('ADM-PLAN-001', $ids, true), 'resilience monitoring capability is preserved');
$planCandidate = $catalog[array_search('ADM-PLAN-001', $ids, true)] ?? [];
$assert(($planCandidate['status'] ?? '') === 'promoted', 'resilience activity monitoring is promoted');
$assert(($planCandidate['target'] ?? '') === '/admin/system-tools/resilience', 'resilience capability points to the read-only activity monitor');
$statusSummary = array_count_values(array_map(static fn(array $candidate): string => (string)$candidate['status'], $catalog));
$assert(($statusSummary['promoted'] ?? 0) === 17, 'all seventeen canonical capability destinations are promoted');
$assert(($statusSummary['implementing'] ?? 0) === 0, 'no catalog candidates remain implementing');
foreach ($catalog as $candidate) {
    $assert(!empty($candidate['source']), (string)$candidate['id'] . ' retains a source path');
    $assert(($candidate['preserve_source'] ?? false) === true, (string)$candidate['id'] . ' preserves source');
    $assert(($inventoryStatuses[(string)$candidate['id']] ?? '') === (string)$candidate['status'], (string)$candidate['id'] . ' UI and inventory status agree');
}
$routes = (string)file_get_contents($root . '/apps/Platform/routes.php');
$publicIndex = (string)file_get_contents($root . '/public/index.php');
$modeRouteStart = strpos($routes, '$router->post(\'/ops/platform-mode-switch\'');
$modeRouteEnd = strpos($routes, '$router->get(\'/ops/platform-mode-switch\'', $modeRouteStart === false ? 0 : $modeRouteStart);
$modeRouteSource = $modeRouteStart !== false && $modeRouteEnd !== false ? substr($routes, $modeRouteStart, $modeRouteEnd - $modeRouteStart) : '';
$selector = (string)file_get_contents($root . '/plugins/Base/Views/ops/platform_mode_selector.php');
$modeService = (string)file_get_contents($root . '/app/Services/PlatformModeService.php');
$modeDecisionService = (string)file_get_contents($root . '/apps/Platform/Services/PlatformModeSwitchDecisionService.php');
$helpers = (string)file_get_contents($root . '/app/Core/helpers.php');
$systemTools = (string)file_get_contents($root . '/plugins/AdminTools/Views/admin/system_tools.php');
$platformOperations = (string)file_get_contents($root . '/apps/Platform/Views/ops/platform_operations.php');
$workbenchService = (string)file_get_contents($root . '/apps/Platform/Services/AdminUpgradeWorkbenchService.php');
$workbenchView = (string)file_get_contents($root . '/apps/Shell/Views/admin/upgrade_workbench.php');
$snapshotService = (string)file_get_contents($root . '/plugins/Base/Services/PlatformAdminStatusSnapshotService.php');
$legacyController = (string)file_get_contents($root . '/plugins/Base/Controllers/RoleDashboardsController.php');
$appAdminScopeService = (string)file_get_contents($root . '/apps/Platform/Services/AppAdminDashboardScopeService.php');
$adminToolsController = (string)file_get_contents($root . '/plugins/AdminTools/Controllers/AdminToolsController.php');
$adminToolsRoutes = (string)file_get_contents($root . '/plugins/AdminTools/routes.php');
$resilienceMap = (string)file_get_contents($root . '/plugins/AdminTools/Views/admin/resilience_map.php');
$resilienceMonitorService = (string)file_get_contents($root . '/plugins/AdminTools/Services/ResilienceActivityMonitorService.php');
$platformLinksCard = (string)file_get_contents($root . '/plugins/AdminTools/SectionCards/PlatformAdminLinksCard.php');
$platformLinksView = (string)file_get_contents($root . '/plugins/AdminTools/Views/admin/platform_admin_links.php');
$adminToolsNavigation = (string)file_get_contents($root . '/plugins/AdminTools/navigation.php');
$enLocale = (string)file_get_contents($root . '/app/Locale/en.php');
$shellHeader = (string)file_get_contents($root . '/public/views/layouts/header.php');
$shellSidebar = (string)file_get_contents($root . '/public/views/layouts/sidebar.php');
$unifiedLauncher = (string)file_get_contents($root . '/apps/Shell/Views/admin/unified_launcher.php');
$shellLayoutCss = (string)file_get_contents($root . '/apps/Shell/styles/shell-layout.css');
$jaLocale = (string)file_get_contents($root . '/app/Locale/ja.php');
$neLocale = (string)file_get_contents($root . '/app/Locale/ne.php');
$setupHealthView = (string)file_get_contents($root . '/public/views/admin/setup/health.php');
$setupEnvironmentView = (string)file_get_contents($root . '/public/views/admin/setup/environment.php');
$setupConfigView = (string)file_get_contents($root . '/public/views/admin/setup/config.php');
$setupReleaseView = (string)file_get_contents($root . '/public/views/admin/setup/release.php');
$setupOverviewView = (string)file_get_contents($root . '/public/views/admin/setup/index.php');
$runtimeReportView = (string)file_get_contents($root . '/plugins/AdminTools/Views/admin/runtime_report.php');
$dataControlView = (string)file_get_contents($root . '/plugins/AdminTools/Views/admin/data_control.php');
$appManagerView = (string)file_get_contents($root . '/public/views/admin/app_manager/index.php');
$notificationsView = (string)file_get_contents($root . '/plugins/Base/Views/notifications.php');
$workspaceProfilesView = (string)file_get_contents($root . '/plugins/Base/Views/ops/workspace_profiles.php');
$userControlView = (string)file_get_contents($root . '/plugins/Base/Views/ops/user_control_board.php');
$auditLogView = (string)file_get_contents($root . '/plugins/Base/Views/ops/audit_log.php');
$accessDetailView = (string)file_get_contents($root . '/plugins/Base/Views/ops/dashboard_assignment_detail_access2.php');
$architectureHealthController = (string)file_get_contents($root . '/app/Admin/ArchitectureHealthController.php');
$architectureHealthView = (string)file_get_contents($root . '/public/views/admin/architecture_health.php');
$routeRegistryView = (string)file_get_contents($root . '/plugins/Base/Views/admin/routes.php');
$baseBuilderView = (string)file_get_contents($root . '/plugins/Base/Views/admin/base_builder.php');
$widgetBuilderView = (string)file_get_contents($root . '/apps/Platform/Views/ops/widget_builder.php');
$widgetBuilderLocale = (string)file_get_contents($root . '/apps/Platform/Resources/lang/en.php');
$organizationView = (string)file_get_contents($root . '/apps/Platform/modules/Organization/Views/index.php');
$organizationNavigation = (string)file_get_contents($root . '/apps/Platform/modules/Organization/navigation.php');
$platformNavigation = (string)file_get_contents($root . '/apps/Platform/navigation.php');
$platformModeView = (string)file_get_contents($root . '/apps/Platform/Views/admin/platform_mode.php');
$navigationTreeView = (string)file_get_contents($root . '/plugins/Base/Views/ops/navigation_tree.php');
$dashboardAssignmentsView = (string)file_get_contents($root . '/plugins/Base/Views/ops/dashboard_assignments.php');
$coreActions = (string)file_get_contents($root . '/app/Actions/actions.php');
$coreDashboardWidgets = (string)file_get_contents($root . '/app/Dashboard/widgets.php');
$shellDashboardWidgets = (string)file_get_contents($root . '/apps/Shell/dashboard_widgets.php');
$adminDashboardPanels = (string)file_get_contents($root . '/apps/Platform/Services/AdminDashboardPanelBlockService.php');
$adminDashboardPanelsView = (string)file_get_contents($root . '/apps/Platform/Views/admin_blocks/admin_dashboard_panels.php');
$adminDashboardView = (string)file_get_contents($root . '/apps/Shell/Views/admin/dashboard.php');
$assert(str_contains($routes, "'/admin/system-tools/upgrade-catalog'"), 'catalog route registered');
$assert(str_contains($publicIndex, 'apps|architecture-health|base|routes|setup|system-tools|platform-admin-links|app-manager'), 'admin username preprocessor excludes Architecture Health');
$assert(str_contains($routes, 'PlatformModeSwitchDecisionService::decide'), 'mode route delegates failure decisions before mutation');
$assert(!str_contains($modeDecisionService, "'/ops/platform-admin-dashboard'") && str_contains($modeDecisionService, "'/admin/system-tools/platform-mode'"), 'mode return path is confined to the canonical workspace');
$assert(str_contains($modeDecisionService, 'PlatformModeService::VALID_MODES'), 'mode decision validates against authoritative mode set');
$assert(str_contains($modeDecisionService, "self::result('csrf_invalid'"), 'CSRF failure returns controlled result code');
$assert(str_contains($modeDecisionService, "self::result('locked'"), 'deployment lock returns controlled result code');
$assert(str_contains($modeDecisionService, "'write_permitted' => \$writePermitted"), 'mode decision explicitly gates mutation permission');
$assert(!str_contains($modeRouteSource, 'getMessage()'), 'mode route does not expose raw exception messages');
$assert(str_contains($selector, 'name="return_to"'), 'selector carries return path');
$assert(str_contains($selector, "t('admin.platform_mode.update')"), 'selector controls localized');
$assert(str_contains($selector, 'isModeSwitchLocked()'), 'selector reads authoritative lock state');
$assert(str_contains($selector, '$platformModeLocked ? \' disabled\''), 'locked selector disables mutation control');
$assert(!str_contains($selector, 'style='), 'Platform Mode selector has no inline presentation rules');
$assert(str_contains($selector, 'platform-mode-option-label'), 'Platform Mode options use Shell-owned presentation');
$assert(str_contains($modeService, 'public static function isModeSwitchLocked(): bool'), 'service exposes read-only lock state');
$assert(str_contains($helpers, "'admin_diagnostics' => ["), 'diagnostic visibility remains mode governed');
$assert(str_contains($systemTools, "'admin.system_tools.section.health_title'"), 'System Tools has a dedicated health group');
$assert(substr_count($systemTools, "'href' => '/admin/setup/health'") === 1, 'platform operational health has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/system-tools/module-health'") === 1, 'module completeness has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/system-tools/runtime-report'") === 1, 'runtime report has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/architecture-health'") === 1, 'architecture health has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/system-tools/export-audit'") === 1, 'export audit has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/system-tools/data-control/audit-trail'") === 1, 'data audit has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/app-manager'") === 1, 'application inventory has one canonical card');
$assert(substr_count($systemTools, "'href' => '/admin/apps/deps'") === 1, 'dependency inspector has one canonical card');
$assert(!str_contains($systemTools, 'admin.system_tools.card.backup_monitoring_future'), 'retired backup monitoring placeholder is removed');
$assert(substr_count($systemTools, "'href' => '/admin/system-tools/resilience'") === 1, 'resilience map has one canonical System Tools card');
$assert(str_contains($adminToolsRoutes, "'/admin/system-tools/resilience'"), 'read-only resilience map route is registered');
$assert(str_contains($adminToolsRoutes, "'resilience_map' => [") && str_contains($adminToolsRoutes, "'mode' => 'read'"), 'resilience map declares read policy');
$assert(!str_contains($resilienceMap, '<form'), 'resilience map owns no mutation form');
$assert(!str_contains($resilienceMap, 'style='), 'resilience map owns no inline presentation');
$assert(str_contains($resilienceMap, "'/admin/system-tools/app-management'"), 'resilience map links canonical app export workflow');
$assert(str_contains($resilienceMap, "'/admin/app-manager'"), 'resilience map links application inventory exports');
$assert(str_contains($resilienceMap, "'/admin/setup/environment'"), 'resilience map links environment snapshot workflow');
$assert(str_contains($resilienceMap, "'/admin/setup/release'"), 'resilience map links release artifact workflow');
$assert(str_contains($resilienceMap, "'/apps/manufacturing/imports'") && str_contains($resilienceMap, "'/apps/manufacturing/restores'"), 'resilience map links Manufacturing import and restore owners');
$assert(str_contains($resilienceMap, "'/apps/sbaio/imports'") && str_contains($resilienceMap, "'/apps/sbaio/restores'"), 'resilience map links SBAIO import and restore owners');
$assert(str_contains($resilienceMap, 'admin.resilience_map.activity_title'), 'resilience map renders unified recent activity');
$assert(str_contains($resilienceMap, 'admin.resilience_map.coverage_title'), 'resilience map renders authoritative source coverage');
$assert(str_contains($resilienceMonitorService, 'ExportHistoryService') && str_contains($resilienceMonitorService, 'ImportHistoryService') && str_contains($resilienceMonitorService, 'RestoreHistoryService'), 'monitor composes export, import, and restore histories');
$assert(str_contains($resilienceMonitorService, 'EnvironmentPortabilityHistoryService') && str_contains($resilienceMonitorService, 'ReleaseHistoryService'), 'monitor composes environment and release histories');
$assert(str_contains($resilienceMonitorService, "'degraded' => \$errors !== []"), 'monitor exposes fail-closed degraded source state');
$assert(str_contains($adminToolsRoutes, "function() use (\$requirePolicyAccess) {\n    \$requirePolicyAccess('app_export_app');"), 'app export handler invokes its declared authorization policy');
$assert(str_contains($adminToolsRoutes, "function() use (\$requirePolicyAccess) {\n    \$requirePolicyAccess('app_export_module');"), 'module export handler invokes its declared authorization policy');
$assert(str_contains($adminToolsRoutes, "function() use (\$requirePolicyAccess) {\n    \$requirePolicyAccess('app_download');"), 'export download handler invokes its declared authorization policy');
$assert(!str_contains($adminToolsRoutes, "\$_SESSION['app_mgmt_err'] = \$e->getMessage()"), 'export failures do not disclose raw exception messages');
$assert(str_contains($adminToolsRoutes, "AdminToolsController::platformAdminLinks(\$v)"), 'retained platform links route uses governed controller rendering');
$assert(!str_contains($adminToolsRoutes, "__DIR__ . '/../SectionCards/PlatformAdminLinksCard.php'"), 'broken legacy platform links include path is removed');
$assert(str_contains($adminToolsNavigation, "'url'        => '/admin/platform-admin-links'") && str_contains($adminToolsNavigation, "'nav_visible' => false"), 'retained platform links stay hidden from primary navigation');
$assert(!str_contains($platformLinksView, '<form') && !str_contains($platformLinksView, 'style='), 'retained platform links review is read-only and class-based');
$assert(str_contains($platformLinksView, '/public/views/layouts/admin-wrapper-open.php'), 'retained platform links use the shared admin wrapper');
foreach (['/ops/access-control', '/ops/workspace-profiles', '/ops/user-dashboard', '/ops/audit-log', '/admin/apps', '/admin/routes', '/admin/base'] as $retainedPlatformUrl) {
    $assert(str_contains($platformLinksCard, "'url' => '{$retainedPlatformUrl}'"), $retainedPlatformUrl . ' remains in compatibility inventory');
}
foreach (['admin.platform_links.title', 'admin.platform_links.status_description', 'admin.platform_links.routes'] as $platformLinksLocaleKey) {
    $assert(str_contains($enLocale, "'{$platformLinksLocaleKey}' =>"), $platformLinksLocaleKey . ' has English translation');
    $assert(str_contains($jaLocale, "'{$platformLinksLocaleKey}' =>"), $platformLinksLocaleKey . ' has Japanese translation');
    $assert(str_contains($neLocale, "'{$platformLinksLocaleKey}' =>"), $platformLinksLocaleKey . ' has Nepali translation');
}
$assert(!str_contains($shellHeader, '$platformModeTone'), 'dormant inline-oriented header mode tone payload is removed');
$assert(str_contains($shellHeader, 'platform-mode-indicator--<?= e($platformMode) ?>'), 'header renders governed read-only mode indicator');
$assert(str_contains($shellHeader, "in_array(\$authorityRoleGlobal, ['platform_admin', 'sysadmin'], true)"), 'header mode indicator is platform-authority confined');
$assert(str_contains($shellHeader, 'href="/admin/system-tools/platform-mode"'), 'header mode indicator opens canonical specialist workspace');
$assert(str_contains($shellLayoutCss, '.platform-mode-indicator--production') && str_contains($shellLayoutCss, '.platform-mode-indicator--development') && str_contains($shellLayoutCss, '.platform-mode-indicator--demo'), 'Shell owns all mode indicator states');
$assert(!str_contains($shellSidebar, '<details class="utility-dev">'), 'empty Developer details placeholder is replaced');
$assert(str_contains($shellSidebar, '#admin-launcher-group-developer'), 'Developer utility points to the unified Developer group');
$assert(!str_contains($shellSidebar, '/admin/architecture-health') && !str_contains($shellSidebar, '/admin/routes'), 'Developer utility does not duplicate specialist tool links');
$assert(str_contains($unifiedLauncher, 'id="admin-launcher-group-<?= e($groupAnchor) ?>"'), 'unified launcher exposes stable group anchors');
foreach (['admin.launcher.open_developer', 'admin.platform_mode.header_aria'] as $shellModeLocaleKey) {
    $assert(str_contains($enLocale, "'{$shellModeLocaleKey}' =>"), $shellModeLocaleKey . ' has English translation');
    $assert(str_contains($jaLocale, "'{$shellModeLocaleKey}' =>"), $shellModeLocaleKey . ' has Japanese translation');
    $assert(str_contains($neLocale, "'{$shellModeLocaleKey}' =>"), $shellModeLocaleKey . ' has Nepali translation');
}
$assert(substr_count($platformOperations, "'href' => '/ops/access-control'") === 1, 'access governance has one overview card');
$assert(substr_count($platformOperations, "'href' => '/ops/user-control'") === 1, 'user lifecycle has one overview card');
$assert(substr_count($platformOperations, "'href' => '/ops/workspace-profiles'") === 1, 'workspace profiles have one overview card');
$assert(substr_count($platformOperations, "'href' => '/ops/audit-log'") === 1, 'audit explorer has one overview card');
$assert(substr_count($platformOperations, "'href' => '/ops/notifications'") === 1, 'administrative notifications have one overview card');
$assert(substr_count($platformOperations, "'href' => '/ops/navigation-tree'") === 1, 'navigation diagnostics have one overview card');
$assert(!str_contains($platformOperations, "'href' => '/ops/platform-admin-dashboard'"), 'Platform Operations no longer emits the duplicate dashboard');
$assert(!str_contains($platformNavigation, "'key' => 'platform_admin_dashboard'"), 'deleted Platform Admin dashboard has no navigation declaration');
$assert(!str_contains($platformModeView, 'href="/ops/platform-admin-dashboard"'), 'Platform Mode no longer emits an always-visible source-dashboard link');
$assert(str_contains($navigationTreeView, 'href="/admin"') && !str_contains($navigationTreeView, 'href="/ops/platform-admin-dashboard"'), 'Navigation Tree returns to Unified Admin');
$assert(str_contains($userControlView, 'href="/admin"') && !str_contains($userControlView, 'href="/ops/platform-admin-dashboard"'), 'User Control returns to Unified Admin');
$assert(str_contains($dashboardAssignmentsView, 'href="/ops/platform-operations"') && !str_contains($dashboardAssignmentsView, 'href="/ops/platform-admin-dashboard"'), 'Access assignments return to Platform Operations');
$assert(str_contains($coreActions, "'target_url' => '/admin'") && !str_contains($coreActions, "'target_url' => '/ops/platform-admin-dashboard'"), 'admin-system action opens Unified Admin');
$assert(!str_contains($coreDashboardWidgets, "'url' => '/ops/platform-admin-dashboard'") && !str_contains($shellDashboardWidgets, "'url' => '/ops/platform-admin-dashboard'"), 'dashboard widget registries no longer emit the duplicate dashboard');
$assert(str_contains($adminDashboardPanels, "'platform_admin' => []"), 'embedded legacy Platform Admin panel is removed from unified home composition');
$assert(str_contains($adminDashboardPanels, "'app_admin' => ['app_admin']"), 'Unified Admin always composes the role-scoped App Admin payload');
$assert(str_contains($adminDashboardPanels, "'sections' => array_values") && str_contains($adminDashboardPanels, "'placeholders' => array_values"), 'App Admin adapter preserves sections and empty/degraded notes');
$assert(!str_contains($adminDashboardPanels, "array_slice((array)(\$payload['cards']"), 'App Admin adapter does not truncate KPI parity');
$assert(str_contains($adminDashboardPanelsView, '$panelSections') && str_contains($adminDashboardPanelsView, '$panelPlaceholders'), 'Unified Admin renders full App Admin scope and empty-state content');
$assert(str_contains($adminDashboardView, '$renderAdminDashboardPanels') && !str_contains($adminDashboardView, 'elseif ($adminDashboardPanels !== []'), 'App Admin panel renders alongside assigned-app widgets');
$assert(str_contains($workbenchService, 'PlatformAdminStatusSnapshotService::snapshot($context)'), 'Platform consumes owner-side snapshot contract');
$assert(str_contains($workbenchService, "require_once \$snapshotServicePath"), 'unified home loads the optional owner snapshot adapter before use');
$assert(!str_contains($workbenchService, 'RoleDashboardsController'), 'Platform workbench does not depend on legacy controller');
$assert(!str_contains($workbenchView, 'mini_action'), 'unified snapshot does not duplicate legacy mutation actions');
$assert(str_contains($workbenchView, "admin.upgrade_workbench.snapshot_title"), 'unified workbench renders read-only platform snapshot');
$assert(str_contains($workbenchView, "\$snapshotState === 'degraded'"), 'unified workbench presents owner snapshot failure explicitly');
$assert(str_contains($workbenchView, 'snapshot_degraded_description'), 'degraded snapshot refuses invented KPI values');
$assert(str_contains($workbenchService, "'show_migration_details' => \$showMigrationDetails"), 'Platform status publishes an explicit migration-evidence boundary');
$assert(str_contains($workbenchView, 'if ($showMigrationDetails)'), 'runtime view gates candidate and migration detail presentation');
$assert(str_contains($workbenchService, "'kicker_key' => 'admin.platform_status.kicker'"), 'graduated status payload uses stable platform identity');
$assert(!str_contains($workbenchView, "t('admin.upgrade_workbench.temporary')"), 'runtime view no longer presents itself as temporary migration control');
foreach (['admin.platform_status.title', 'admin.platform_status.description', 'admin.platform_status.status.operational', 'admin.app_admin_status.title'] as $statusLocaleKey) {
    $assert(str_contains($enLocale, "'{$statusLocaleKey}' =>"), $statusLocaleKey . ' has English translation');
    $assert(str_contains($jaLocale, "'{$statusLocaleKey}' =>"), $statusLocaleKey . ' has Japanese translation');
    $assert(str_contains($neLocale, "'{$statusLocaleKey}' =>"), $statusLocaleKey . ' has Nepali translation');
}
$assert(str_contains($snapshotService, "'schema_sync_gaps' => ['admin.upgrade_workbench.metric.schema_gaps', '/admin/base']"), 'schema gaps use stable key and Base handoff');
$assert(str_contains($snapshotService, "'failed_migrations' => ['admin.upgrade_workbench.metric.failed_migrations', '/admin/apps']"), 'failed migrations use stable key and Apps handoff');
$assert(str_contains($snapshotService, "'module_visibility_rules' => ['admin.upgrade_workbench.metric.visibility_rules', '/ops/navigation-tree']"), 'visibility metric uses stable key and diagnostics handoff');
$assert(str_contains($legacyController, "'key' => 'active_apps'"), 'legacy provider publishes stable card keys');
$assert(str_contains($legacyController, "'key' => 'environment'"), 'legacy provider publishes stable section keys');
$assert(str_contains($legacyController, "AppAdminDashboardScopeService::allowsApp(\$ctx, 'manufacturing')"), 'App Admin Manufacturing rollups require assigned-app scope');
$assert(str_contains($legacyController, 'genericAppAdminDashboard($assignedApps)'), 'non-Manufacturing App Admin receives a fail-closed generic payload');
$assert(str_contains($appAdminScopeService, "return array_values(array_filter(array_unique(\$apps)"), 'App Admin scope normalizes and deduplicates assigned applications');
$assert(!str_contains((string)file_get_contents($root . '/plugins/Base/Views/ops/role_dashboard.php'), 'style='), 'retained role dashboards have no inline presentation rules');
$roleDashboardView = (string)file_get_contents($root . '/plugins/Base/Views/ops/role_dashboard.php');
$assert(!str_contains($roleDashboardView, "'platform_admin' => [") && !str_contains($roleDashboardView, "'app_admin' => ["), 'retired admin dashboards are removed from the shared role-dashboard view');
$assert(!str_contains($roleDashboardView, 'role-dashboard-compatibility'), 'retired compatibility banner markup is removed');
$assert(!str_contains($legacyController, 'Central backup/export job monitoring remains planned'), 'retired legacy monitoring placeholder is removed');
$assert(!str_contains($workbenchView, '<form'), 'unified KPI snapshot contains no mutation form');
$assert(str_contains($adminToolsController, "should_show_feature('admin_tools')"), 'System Tools presentation observes mode visibility');
$assert(str_contains($systemTools, "'visibility' => 'developer_tools'"), 'developer-only System Tools cards declare visibility');
$assert(str_contains($systemTools, 'if ($developerToolsVisible)'), 'developer-only catalog action is presentation filtered');
foreach ($catalog as $candidate) {
    $labelKey = (string)$candidate['labelKey'];
    $assert(str_contains($jaLocale, "'{$labelKey}' =>"), $labelKey . ' has Japanese translation');
    $assert(str_contains($neLocale, "'{$labelKey}' =>"), $labelKey . ' has Nepali translation');
}
$assert(!str_contains($setupHealthView, 'style='), 'Platform Health view has no inline presentation rules');
$assert(str_contains($setupHealthView, "t('admin.setup_health.title')"), 'Platform Health title is localized');
$assert(str_contains($setupHealthView, '$healthStatusLabel'), 'Platform Health statuses use localized presentation');
$assert(str_contains($setupHealthView, 'setup-health-grid'), 'Platform Health uses shared layout classes');
$assert(!str_contains($setupEnvironmentView, 'style='), 'Environment portability view has no inline presentation rules');
$assert(str_contains($setupEnvironmentView, "t('admin.setup_environment.title')"), 'Environment portability title is localized');
$assert(str_contains($setupEnvironmentView, 'setup-environment-grid'), 'Environment portability uses shared layout classes');
$assert(str_contains($setupEnvironmentView, 'action="/admin/setup/environment/snapshot"'), 'snapshot creation action is preserved');
$assert(str_contains($setupEnvironmentView, 'action="/admin/setup/environment/preview"'), 'clone preview action is preserved');
$assert(str_contains($setupEnvironmentView, 'action="/admin/setup/environment/apply"'), 'controlled clone apply action is preserved');
$assert(str_contains($setupEnvironmentView, 'action="/admin/setup/environment/cancel"'), 'clone review cancellation is preserved');
$assert(substr_count($setupEnvironmentView, 'name="csrf"') === 4, 'all Environment mutation forms retain CSRF fields');
$assert(substr_count($setupEnvironmentView, 'name="preview_token"') === 2, 'apply and cancel retain preview-token confinement');
$assert(str_contains($setupEnvironmentView, '/admin/setup/environment/download?id='), 'snapshot history download remains available');
$assert(str_contains($setupEnvironmentView, 'name="conflict_strategy"'), 'clone apply retains explicit conflict strategy');
$assert(str_contains($setupEnvironmentView, 'name="install_missing_dependencies"'), 'clone apply retains dependency choice');
$assert(!str_contains($setupOverviewView, 'style='), 'Setup Overview has no inline presentation rules');
$assert(str_contains($setupOverviewView, '$setupStatusClass'), 'Setup Overview maps structured statuses to governed classes');
$assert(str_contains($setupOverviewView, 'action="/admin/setup/profile"'), 'Setup profile execution remains connected');
$assert(!str_contains($setupConfigView, 'style='), 'Configuration view has no inline presentation rules');
$assert(str_contains($setupConfigView, "t('admin.setup_config.title')"), 'Configuration title is localized');
$assert(str_contains($setupConfigView, 'action="/admin/setup/config/save"'), 'configuration save action is preserved');
$assert(str_contains($setupConfigView, 'action="/admin/setup/config/import?environment='), 'configuration import action is preserved');
$assert(substr_count($setupConfigView, 'name="csrf"') === 2, 'configuration mutation forms retain CSRF fields');
$assert(str_contains($setupConfigView, "preg_match('/password|passwd|secret|token|credential|(?:private|api|access|encryption)[_-]?key/i'"), 'read-only configuration previews mask sensitive values');
$assert(str_contains($setupConfigView, '/admin/setup/config/export?environment='), 'configuration export remains connected');
$assert(!str_contains($setupReleaseView, 'style='), 'Release view has no inline presentation rules');
$assert(str_contains($setupReleaseView, "t('admin.setup_release.title')"), 'Release title is localized');
$assert(str_contains($setupReleaseView, 'action="/admin/setup/release/preview"'), 'release readiness action is preserved');
$assert(str_contains($setupReleaseView, 'action="/admin/setup/release/generate"'), 'release generation action is preserved');
$assert(str_contains($setupReleaseView, 'action="/admin/setup/release/cancel"'), 'release preview cancellation is preserved');
$assert(substr_count($setupReleaseView, 'name="csrf"') === 3, 'release mutation forms retain CSRF fields');
$assert(substr_count($setupReleaseView, 'name="preview_token"') === 2, 'generate and cancel retain release preview-token confinement');
$assert(str_contains($setupReleaseView, '/admin/setup/release/download?id='), 'release package download remains available');
$assert(!str_contains($runtimeReportView, 'style='), 'Runtime Report has no inline presentation rules');
$assert(str_contains($runtimeReportView, 'admin.runtime_report.value.yes'), 'Runtime Report boolean presentation is localized');
$assert(str_contains($runtimeReportView, '/admin/system-tools/runtime-report?export=text'), 'Runtime Report text export remains connected');
$assert(!str_contains($dataControlView, 'style='), 'Data Control entry has no inline presentation rules');
$assert(str_contains($dataControlView, '/admin/system-tools/data-control/browse?table='), 'Data Control browse handoff remains connected');
$assert(str_contains($dataControlView, '/admin/system-tools/data-control/preview-mutation?table='), 'Data Control preview handoff remains connected');
$assert(str_contains($dataControlView, '/admin/system-tools/data-control/approvals'), 'Data Control approval queue remains connected');
$assert(str_contains($dataControlView, '/admin/system-tools/data-control/audit-trail'), 'Data Control audit trail remains connected');
$assert(!str_contains($appManagerView, 'style='), 'App Manager inventory has no inline presentation rules');
$assert(str_contains($appManagerView, 'action="/admin/app-manager/upload"'), 'App Manager upload action is preserved');
$assert(str_contains($appManagerView, 'action="/admin/app-manager/action"'), 'App Manager lifecycle action is preserved');
$assert(substr_count($appManagerView, 'name="csrf"') === 2, 'App Manager mutation form templates retain CSRF fields');
$assert(str_contains($appManagerView, 'onclick="return confirm('), 'destructive App Manager actions retain confirmation');
$assert(str_contains($appManagerView, '/admin/app-manager/export?app_key='), 'App Manager export remains connected');
$assert(!str_contains($notificationsView, '<style>'), 'Notifications no longer owns embedded runtime presentation');
$assert(!str_contains($notificationsView, '>Send Message<'), 'Notifications compose action is localized');
$assert(str_contains($notificationsView, 'action="/ops/notifications/send-message"'), 'administrative notification compose remains connected');
$assert(str_contains($notificationsView, 'action="/ops/notifications/read-all"'), 'notification bulk-read action remains connected');
$assert(str_contains($notificationsView, 'action="/ops/notifications/dismiss"'), 'notification dismissal remains connected');
$assert(substr_count($notificationsView, 'name="csrf"') === 4, 'notification mutation form templates retain CSRF fields');
$assert(!str_contains($workspaceProfilesView, 'style='), 'Workspace Profiles has no inline presentation rules');
$assert(str_contains($workspaceProfilesView, 'action="/ops/workspace-profiles/delete"'), 'workspace profile deletion remains connected');
$assert(str_contains($workspaceProfilesView, 'onsubmit="return confirm('), 'workspace profile deletion retains confirmation');
$assert(str_contains($userControlView, "t('admin.user_control.open_user_detail'"), 'User Control row accessibility label is localized');
$assert(str_contains($userControlView, 'action="/ops/user-control/user/create"'), 'user creation remains connected');
$assert(str_contains($auditLogView, "t('ops.audit_log.filter_app')"), 'Audit scope application label is localized');
$assert(str_contains($auditLogView, 'action="/ops/audit-log"'), 'Audit filtering remains connected');
$assert(str_contains($accessDetailView, 'action="/ops/access-control/app-role/delete"'), 'Access Governance app-role deletion remains connected');
$assert(str_contains($accessDetailView, 'onsubmit="return confirm('), 'Access Governance destructive app-role action retains confirmation');
$assert(str_contains($architectureHealthController, "loadLocale('ne')"), 'Architecture Health measures Nepali locale coverage');
$assert(str_contains($architectureHealthView, "t('admin.architecture_health.title')"), 'Architecture Health title is localized');
$assert(str_contains($architectureHealthView, '/public/views/layouts/admin-wrapper-open.php'), 'Architecture Health uses the unified admin wrapper');
$assert(!str_contains($architectureHealthView, 'style='), 'Architecture Health has no inline presentation rules');
$assert(str_contains($architectureHealthView, "['widget' => 0, 'dashboard' => 0]"), 'Architecture Health contract metrics derive real surface counts');
$assert(!str_contains($routeRegistryView, '<style>'), 'Route Registry no longer owns embedded presentation');
$assert(!str_contains($routeRegistryView, 'style='), 'Route Registry has no inline presentation rules');
$assert(str_contains($routeRegistryView, '$routeStatusLabel'), 'Route Registry presents localized route states');
$assert(str_contains($baseBuilderView, 'action="/admin/base/schema-sync-bulk"'), 'Base Builder bulk schema synchronization remains connected');
$assert(str_contains($baseBuilderView, 'action="/admin/base/schema-sync"'), 'Base Builder single schema synchronization remains connected');
$assert(str_contains($baseBuilderView, 'action="/admin/base/field/save"'), 'Base Builder field metadata save remains connected');
$assert(str_contains($baseBuilderView, 'action="/admin/base/field/disable"'), 'Base Builder guarded field disable remains connected');
$assert(substr_count($baseBuilderView, 'name="csrf"') === 5, 'Base Builder mutation form templates retain CSRF fields');
$assert(str_contains($baseBuilderView, "t('base.db_control.confirm_schema_sync')"), 'Base Builder schema synchronization confirmation is localized');
$assert(!str_contains($widgetBuilderView, 'style='), 'Widget Builder has no inline presentation rules');
$assert(str_contains($widgetBuilderView, 'action="/ops/widget-builder/save"'), 'Widget Builder save remains connected');
$assert(str_contains($widgetBuilderView, 'action="/ops/widget-builder/bulk-publish"'), 'Widget Builder bulk publish remains connected');
$assert(str_contains($widgetBuilderView, 'action="/ops/widget-builder/clone"'), 'Widget Builder clone remains connected');
$assert(str_contains($widgetBuilderView, 'action="/ops/widget-builder/archive"'), 'Widget Builder archive remains connected');
$assert(substr_count($widgetBuilderView, 'name="csrf"') === 8, 'Widget Builder mutation form templates retain CSRF fields');
$assert(str_contains($widgetBuilderLocale, "'ops.widget_builder.title' => 'Widget Builder'"), 'Widget Builder runtime locale catalog is registered');
$assert(str_contains($widgetBuilderView, 'container.hidden = !shouldShow'), 'Widget Builder conditional controls use semantic hidden state');
$assert(!str_contains($organizationView, 'style='), 'Organization overview has no inline presentation rules');
$assert(str_contains($organizationView, '/ops/organization/company'), 'Organization company workspace remains connected');
$assert(str_contains($organizationView, '/ops/organization/branches'), 'Organization branch workspace remains connected');
$assert(str_contains($organizationView, '/ops/organization/fiscal'), 'Organization fiscal workspace remains connected');
$assert(str_contains($organizationView, '/ops/organization/branding'), 'Organization branding workspace remains connected');
$assert(str_contains($organizationNavigation, 'organization.nav.admin_overview'), 'admin launcher distinguishes Organization Overview from generic overview links');
echo "Admin upgrade catalog probe: {$checks}/{$checks} assertions passed\n";
