<?php
return [
    'tool_key' => 'import_export_mapper',
    'key' => 'import_export_mapper',
    'label' => 'Import / Export Mapper',
    'name' => 'Import / Export Mapper',
    'name_key' => 'studio.tool.import_export_mapper.name',
    'description_key' => 'studio.tool.import_export_mapper.description',
    'category' => 'authoring',
    'home_group' => 'data_logic',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/import-export-mapper',
    'placeholder' => true,
    'risk_level' => 'medium',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/import-export-mapper'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['import_map', 'export_map', 'schema', 'report'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
