<?php
return [
    'key' => 'report_builder',
    'name' => 'Report Builder',
    'name_key' => 'studio.tool.report_builder.name',
    'description_key' => 'studio.tool.report_builder.description',
    'category' => 'authoring',
    'home_group' => 'design_content',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/report-designer',
    'placeholder' => false,
    'visible_on_home' => false,
    'risk_level' => 'medium',
    'default_enabled' => false,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [],
    'views' => [],
    'services' => [],
    'owner' => 'studio',
    'migration' => [
        'status' => 'replaced',
        'replaced_by' => 'report_designer',
        'note' => 'Report Designer is the canonical report authoring tool.',
    ],
    'can_load' => ['report', 'view', 'dashboard'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
