<?php
declare(strict_types=1);
use Apps\Studio\Tools\OwnerStructureScan\Services\OwnerStructureDeletionSnapshotReadinessWorkspaceService;
require_once dirname(__DIR__) . '/Tools/OwnerStructureScan/Services/OwnerStructureDeletionSnapshotReadinessWorkspaceService.php';
$passes=0;$fails=0;$assert=static function(bool $c,string $m)use(&$passes,&$fails):void{if($c){$passes++;echo"PASS: $m\n";}else{$fails++;echo"FAIL: $m\n";}};
$owners=[['owner_key'=>'Manufacturing/Products','owner_type'=>'module','root_path'=>'apps/Manufacturing/modules/Products']];
$changeSet=['change_set_fingerprint'=>'deletion-change-set:current','target'=>['owner_key'=>'Manufacturing/Products','target_path'=>'apps/Manufacturing/modules/Products']];
$approval=['readiness_fingerprint'=>'deletion-execution-readiness:current'];
$dryRun=['dry_run_fingerprint'=>'deletion-execution-dry-run:current'];
$executorReadiness=['request_evidence'=>['request_id'=>'request-current']];
$actor=['user_id'=>'executor-42','authority_role'=>'platform_admin'];
$claim=['claim_id'=>'claim-current'];
$assessment=['status'=>'ok','snapshot_readiness'=>'ready','snapshot_ready'=>'yes','claim_valid'=>'yes','executor_identity_valid'=>'yes','source_available'=>'yes','destination_available'=>'yes','current_packet'=>['change_set_fingerprint'=>'deletion-change-set:current'],'claim_evidence'=>['claim_id'=>'claim-current'],'actor_evidence'=>['actor_id'=>'executor-42'],'snapshot_contract'=>['destination_path'=>'storage/studio/deletion-execution-snapshots/x'],'preflight_checks'=>[['check_id'=>'one']],'blocking_reasons'=>[],'snapshot_readiness_fingerprint'=>'deletion-snapshot-readiness:workspace','diagnostics'=>[]];
$readerCalls=0;$assessorCalls=0;
$reader=static function(string $requestId,?string $root)use(&$readerCalls,$claim):array{$readerCalls++;if($requestId!=='request-current')throw new RuntimeException('wrong request');return $claim;};
$assessor=static function(array $owner,array $cs,array $ar,array $dr,array $er,?array $cl,?array $act,?string $root)use(&$assessorCalls,$assessment):array{$assessorCalls++;if(($owner['owner_key']??'')!=='Manufacturing/Products'||($cl['claim_id']??'')!=='claim-current')throw new RuntimeException('wrong inputs');return $assessment;};
$idle=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Manufacturing/Products',false,$changeSet,$approval,$dryRun,$executorReadiness,$actor,null,$reader,$assessor);
$assert(($idle['status']??'')==='idle','idle workspace stays idle');$assert(($idle['assessment']??null)===null,'idle has no assessment');$assert($readerCalls===0&&$assessorCalls===0,'idle performs no reads');
$ready=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Manufacturing/Products',true,$changeSet,$approval,$dryRun,$executorReadiness,$actor,null,$reader,$assessor);
$assert(($ready['status']??'')==='ready','requested workspace ready');$assert($readerCalls===1,'claim reader called once');$assert($assessorCalls===1,'assessor called once');
$assert(($ready['snapshot_readiness']??'')==='ready','snapshot state exposed');$assert(($ready['snapshot_ready']??'')==='yes','snapshot readiness exposed');$assert(($ready['claim_valid']??'')==='yes','claim validity exposed');$assert(($ready['executor_identity_valid']??'')==='yes','executor validity exposed');$assert(($ready['source_available']??'')==='yes','source availability exposed');$assert(($ready['destination_available']??'')==='yes','destination availability exposed');$assert(($ready['claim_evidence']['claim_id']??'')==='claim-current','claim evidence exposed');$assert(($ready['actor_evidence']['actor_id']??'')==='executor-42','actor evidence exposed');$assert(($ready['snapshot_contract']['destination_path']??'')==='storage/studio/deletion-execution-snapshots/x','snapshot contract exposed');$assert(count($ready['preflight_checks']??[])===1,'checks exposed');$assert(($ready['snapshot_readiness_fingerprint']??'')==='deletion-snapshot-readiness:workspace','fingerprint exposed');
$missingOwner=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Missing/Owner',true,$changeSet,$approval,$dryRun,$executorReadiness,$actor);
$assert(($missingOwner['status']??'')==='error','missing owner fails safely');$assert(($missingOwner['diagnostics'][0]['code']??'')==='OSS_DELETION_SNAPSHOT_READINESS_OWNER_UNAVAILABLE','missing owner diagnostic explicit');
$missing=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Manufacturing/Products',true,null,$approval,$dryRun,$executorReadiness,$actor);
$assert(($missing['status']??'')==='error','missing prerequisite fails safely');$assert(($missing['diagnostics'][0]['code']??'')==='OSS_DELETION_SNAPSHOT_READINESS_PREREQUISITES_REQUIRED','prerequisite diagnostic explicit');
$badPacket=$executorReadiness;$badPacket['request_evidence']['request_id']='';
$invalid=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Manufacturing/Products',true,$changeSet,$approval,$dryRun,$badPacket,$actor);
$assert(($invalid['status']??'')==='error','missing request identity fails safely');$assert(($invalid['diagnostics'][0]['code']??'')==='OSS_DELETION_SNAPSHOT_READINESS_PACKET_INVALID','packet diagnostic explicit');
$bad=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Manufacturing/Products',true,$changeSet,$approval,$dryRun,$executorReadiness,$actor,null,static fn():?array=>null,static fn():string=>'bad');
$assert(($bad['status']??'')==='error','invalid assessor result fails safely');$assert(($bad['diagnostics'][0]['code']??'')==='OSS_DELETION_SNAPSHOT_READINESS_RESULT_INVALID','invalid result diagnostic explicit');
$thrown=OwnerStructureDeletionSnapshotReadinessWorkspaceService::build($owners,'Manufacturing/Products',true,$changeSet,$approval,$dryRun,$executorReadiness,$actor,null,static function():array{throw new RuntimeException('snapshot readiness failure');},$assessor);
$assert(($thrown['status']??'')==='error','reader exception fails safely');$assert(($thrown['diagnostics'][0]['code']??'')==='OSS_DELETION_SNAPSHOT_READINESS_FAILED','reader exception diagnostic explicit');$assert(($thrown['diagnostics'][0]['message']??'')==='snapshot readiness failure','exception message preserved');
$postludes=['preview.postlude.zzzzzzzz-deletion-execution-claim.php','preview.postlude.zzzzzzzzz-deletion-snapshot-readiness.php'];sort($postludes,SORT_NATURAL|SORT_FLAG_CASE);
$assert($postludes[1]==='preview.postlude.zzzzzzzzz-deletion-snapshot-readiness.php','snapshot readiness loads after claim');
$source=file_get_contents(dirname(__DIR__).'/Tools/OwnerStructureScan/Services/OwnerStructureDeletionSnapshotReadinessWorkspaceService.php');
$assert(is_string($source)&&!preg_match('/file_put_contents|fwrite|unlink\s*\(|rename\s*\(|mkdir\s*\(|rmdir\s*\(|copy\s*\(|PDO|INSERT\s+INTO|UPDATE\s+.+SET|DELETE\s+FROM/i',$source),'workspace has no mutation implementation');
echo"\nResults: $passes passed, $fails failed\n";exit($fails?1:0);
