<?php
return [
    'tool_key' => 'token_impact_explorer',
    'key' => 'token_impact_explorer',
    'label' => 'Token Impact Explorer',
    'name' => 'Token Impact Explorer',
    'name_key' => 'studio.tool.token_impact_explorer.name',
    'description_key' => 'studio.tool.token_impact_explorer.description',
    'category' => 'inspection',
    'home_group' => 'governance',
    'canonical_route' => '/apps/studio/tools/customization-studio/diagnose/token-impact-explorer',
    'placeholder' => false,
    'risk_level' => 'low',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.tools.token_impact_explorer.use'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/customization-studio/diagnose/token-impact-explorer'],
    'views' => ['apps/Studio/Tools/CustomizationStudio/Diagnose/TokenImpactExplorer/Views/impact-explorer.php'],
    'services' => [
        'Apps\\Studio\\Controllers\\StudioController::tokenImpactExplorerPreview',
    ],
    'owner' => 'studio',
    'status' => 'active',
    'can_load' => ['css', 'view'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => false,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
