<?php
return [
    'key' => 'db_schema_tool',
    'name' => 'DB Schema Tool',
    'name_key' => 'studio.tool.db_schema_tool.name',
    'description_key' => 'studio.tool.db_schema_tool.description',
    'category' => 'authoring',
    'home_group' => 'data_logic',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/db-schema-tool',
    'placeholder' => true,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging'],
    'routes' => ['/apps/studio/tools/db-schema-tool'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['db_schema', 'module', 'app'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
