<?php
return [
    'tool_key' => 'report_designer',
    'key' => 'report_designer',
    'label' => 'Report Designer',
    'name' => 'Report Designer',
    'name_key' => 'studio.tool.report_designer.name',
    'description_key' => 'studio.tool.report_designer.description',
    'category' => 'authoring',
    'home_group' => 'design_content',
    'canonical_route' => '/apps/studio/tools/report-designer',
    'placeholder' => false,
    'migration' => [
        'status' => 'canonical',
        'replaces' => 'report_builder',
        'note' => 'Existing report work is being consolidated into Report Designer.',
    ],
    'risk_level' => 'low',
    'default_enabled' => false,
    'can_disable' => true,
    'required_permissions' => ['studio.tools.report_designer.use'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/report-designer',
        '/apps/studio/tools/report-designer/save',
    ],
    'views' => ['apps/Studio/Tools/ReportDesigner/Views/index.php'],
    'services' => [
        'Apps\\Studio\\Controllers\\StudioController::reportDesignerPreview',
        'Apps\\Studio\\Controllers\\StudioController::reportDesignerSaveDefinition',
        'Platform\\Reports\\ReportDefinitionValidator',
        'Platform\\Reports\\ReportDefinitionRepository',
    ],
    'owner' => 'studio',
    'status' => 'active',
    'can_load' => ['report'],
    'can_modify' => true,
    'requires_approval' => false,
    'writes_to_owner_artifact' => true,
    'supports_diff' => false,
    'supports_snapshot' => true,
    'supports_rollback' => false,
];
