<?php
return [
    'tool_key' => 'integration_designer',
    'key' => 'integration_designer',
    'label' => 'Integration Designer',
    'name' => 'Integration Designer',
    'name_key' => 'studio.tool.integration_designer.name',
    'description_key' => 'studio.tool.integration_designer.description',
    'category' => 'authoring',
    'home_group' => 'data_logic',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/integration-designer',
    'placeholder' => true,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging'],
    'routes' => ['/apps/studio/tools/integration-designer'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['integration', 'connector', 'webhook', 'api_contract'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
