<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-open.php'; ?>
<?php
$gov = is_array($governance ?? null) ? $governance : [];
$approvalEvents = is_array($approval_events ?? null) ? $approval_events : [];
$activityTimeline = is_array($activity_timeline ?? null) ? $activity_timeline : [];
$isLocked = !empty($gov['locked']);
$canEditPlan = !empty($can_edit_plan);
$canEditAddedBy = !empty($can_edit_added_by);
$readOnlyAll = $isLocked || (!$canEditPlan && !$canEditAddedBy);
$statusOptions = ['Draft', 'Planned', 'In Progress', 'Completed', 'On Hold', 'Cancelled'];
$isAdmin = function_exists('base_is_admin_user') ? base_is_admin_user() : false;
$statusLabelMap = [
	'Draft' => t('module.production_plans.status.draft'),
	'Planned' => t('module.production_plans.status.planned'),
	'In Progress' => t('module.production_plans.status.in_progress'),
	'Completed' => t('module.production_plans.status.completed'),
	'On Hold' => t('module.production_plans.status.on_hold'),
	'Cancelled' => t('module.production_plans.status.cancelled'),
];
?>
<div class="card"><div class="row u-style-2d7d2729a4"><h2 class="u-style-1169661891"><?= e(t('module.production_plans.title')) ?> #<?= (int)$row['id'] ?></h2><div class="row u-style-f0abc1db33"><a class="btn" href="/production-plans/print-pdf?id=<?= (int)$row['id'] ?>" target="_blank" rel="noopener"><?= e(t('common.print_pdf')) ?></a><a class="btn" href="/production-plans/download-pdf?id=<?= (int)$row['id'] ?>"><?= e(t('common.download_pdf')) ?></a><a class="btn" href="/production-plans"><?= e(t('common.back_to_list')) ?></a><?php if ($isAdmin): ?><a class="btn" style="background: var(--style-subtle-bg);color: var(--text);border-color: var(--style-border-soft);" href="/admin/system-tools/stage-inspector?inspect_entity=ProductionPlan&inspect_id=<?= (int)$row['id'] ?>" target="_blank" title="<?= e(t('module.production_plans.stage_inspector_title')) ?>"><?= e(t('module.production_plans.stage_inspector')) ?></a><?php endif; ?></div></div></div>
<?php if (!($pdf_ready ?? false)): ?><div class="card dsp-flash-err"><?= e(t('common.pdf_not_available')) ?></div><?php endif; ?>
<?php $error = isset($error) ? (string)$error : ''; ?>
<?php if ($error !== ''): ?><div class="card dsp-flash-err"><?= e($error) ?></div><?php endif; ?>
<?php $ownership_title = t('module.production_plans.operational_ownership'); require APP_ROOT . '/public/views/partials/ownership_summary.php'; ?>
<div class="card">
	<div class="row u-style-91ebbdc206">
		<div class="ui-block"><strong><?= e(t('module.production_plans.approval')) ?>:</strong> <?= e((string)($statusLabelMap[(string)($row['approval_status'] ?? 'Draft')] ?? (string)($row['approval_status'] ?? 'Draft'))) ?> | <strong><?= e(t('module.production_plans.locked_label')) ?>:</strong> <?= $isLocked ? e(t('module.production_plans.yes')) : e(t('module.production_plans.no')) ?></div>
		<div class="muted"><?= e(t('module.production_plans.added_by')) ?> <?= e((string)($row['added_by'] ?? '-')) ?> | <?= e(t('module.production_plans.approved_by')) ?> <?= e((string)($row['approved_by'] ?? '-')) ?> <?= e(t('module.production_plans.at')) ?> <?= e((string)($row['approved_at'] ?? '-')) ?></div>
	</div>
	<?php if ($isLocked): ?><div class="card u-style-f47b09d788"><?= e(t('module.production_plans.locked_notice')) ?></div><?php endif; ?>
	<?php if (!$canEditPlan && !$canEditAddedBy): ?><div class="card u-style-d60e50b0d3"><?= e(t('module.production_plans.view_only_notice')) ?></div><?php endif; ?>
	<?php if (!$canEditPlan && $canEditAddedBy): ?><div class="card u-style-d60e50b0d3"><?= e(t('module.production_plans.added_by_only_notice')) ?></div><?php endif; ?>
	<div class="row u-style-8bb0cda49c">
		<?php if (!empty($gov['can_submit'])): ?><form class="u-style-ed6103acbe" method="post" action="/production-plans/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="submit"><input class="input" name="note" placeholder="<?= e(t('module.production_plans.placeholder.submit_note')) ?>"><button class="btn" type="submit"><?= e(t('module.production_plans.action.submit_for_approval')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_approve'])): ?><form class="u-style-ed6103acbe" method="post" action="/production-plans/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="approve"><input class="input" name="note" placeholder="<?= e(t('module.production_plans.placeholder.approval_note')) ?>"><button class="btn ok" type="submit"><?= e(t('module.production_plans.action.approve')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_reject'])): ?><form class="u-style-ed6103acbe" method="post" action="/production-plans/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="reject"><input class="input" name="reason" placeholder="<?= e(t('module.production_plans.placeholder.reject_reason')) ?>" required><input class="input" name="note" placeholder="<?= e(t('module.production_plans.placeholder.optional_note')) ?>"><button class="btn" type="submit"><?= e(t('module.production_plans.action.reject')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_reopen'])): ?><form class="u-style-ed6103acbe" method="post" action="/production-plans/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="reopen"><input class="input" name="reason" placeholder="<?= e(t('module.production_plans.placeholder.reopen_reason')) ?>" required><input class="input" name="note" placeholder="<?= e(t('module.production_plans.placeholder.optional_note')) ?>"><button class="btn" type="submit"><?= e(t('module.production_plans.action.reopen')) ?></button></form><?php endif; ?>
		<?php if (!empty($gov['can_override'])): ?><form class="u-style-ed6103acbe" method="post" action="/production-plans/approval-action"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="action" value="unlock_override"><input class="input" name="reason" placeholder="<?= e(t('module.production_plans.placeholder.override_reason')) ?>" required><button class="btn" type="submit"><?= e(t('module.production_plans.action.unlock_override')) ?></button></form><?php endif; ?>
	</div>
	<?php if (!$canEditPlan && $canEditAddedBy): ?>
	<form method="post" action="/production-plans/edit" class="row u-style-761d3addb2"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>">
		<div class="u-style-6c0d09d5fa"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.added_by')) ?></label><input class="input" name="added_by" value="<?= e((string)($row['added_by'] ?? '')) ?>" <?= $isLocked ? 'readonly' : '' ?>></div>
		<div class="row u-style-0466783d98"><button class="btn ok" type="submit" <?= $isLocked ? 'disabled' : '' ?>><?= e(t('module.production_plans.update_added_by')) ?></button></div>
	</form>
	<?php endif; ?>
<form method="post" action="/production-plans/edit" class="row"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><fieldset <?= $readOnlyAll ? 'disabled' : '' ?> style="border:0;padding:0;margin:0;display:contents">
<div class="u-style-a17b2f9a1e"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.plan_date_required')) ?></label><input class="input" type="date" name="plan_date" required value="<?= e((string)$row['plan_date']) ?>"></div>
<div class="u-style-6c0d09d5fa"><label class="muted u-style-98847c28df"><?= e(t('common.machine')) ?> *</label><select class="u-style-81a7ab4e7d" name="machine_id" required><?php foreach ($machines as $m): ?><option value="<?= (int)$m['id'] ?>" <?= ((int)$row['machine_id'] === (int)$m['id']) ? 'selected' : '' ?>><?= e((string)$m['machine_no']) ?> - <?= e((string)$m['machine_name']) ?></option><?php endforeach; ?></select></div>
<div class="u-style-6c0d09d5fa"><label class="muted u-style-98847c28df"><?= e(t('common.part')) ?> *</label><select class="u-style-81a7ab4e7d" name="product_id" required><?php foreach ($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= ((int)$row['product_id'] === (int)$p['id']) ? 'selected' : '' ?>><?= e((string)$p['parts_name']) ?> (<?= e((string)$p['parts_number']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-aae0403196"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.planned_qty_required')) ?> *</label><input class="input" type="number" step="0.01" name="planned_qty" required value="<?= e((string)$row['planned_qty']) ?>"></div>
<div class="u-style-f09611ef0f"><label class="muted u-style-98847c28df"><?= e(t('common.sequence')) ?></label><input class="input" type="number" name="sequence_no" value="<?= e((string)$row['sequence_no']) ?>"></div>
<div class="u-style-ead6a4fcdb"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.runtime')) ?></label><input class="input" type="number" step="0.01" name="runtime" value="<?= e((string)($row['runtime'] ?? '')) ?>"></div>
<div class="u-style-a17b2f9a1e"><label class="muted u-style-98847c28df"><?= e(t('common.status')) ?></label><select class="u-style-81a7ab4e7d" name="status"><?php foreach ($statusOptions as $opt): ?><option value="<?= e($opt) ?>" <?= ((string)$row['status'] === $opt) ? 'selected' : '' ?>><?= e((string)($statusLabelMap[$opt] ?? $opt)) ?></option><?php endforeach; ?></select></div>
<div class="u-style-4ad81db508"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.plan_type')) ?></label><input class="input" name="plan_type" value="<?= e((string)$row['plan_type']) ?>"></div>
<div class="u-style-a17b2f9a1e"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.reference_doctype')) ?></label><input class="input" name="reference_doctype" value="<?= e((string)($row['reference_doctype'] ?? '')) ?>"></div>
<div class="u-style-a17b2f9a1e"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.reference_name')) ?></label><input class="input" name="reference_name" value="<?= e((string)($row['reference_name'] ?? '')) ?>"></div>
<div class="u-style-aae0403196"><label class="muted u-style-98847c28df"><?= e(t('common.coverage')) ?> %</label><input class="input" type="number" step="0.01" name="coverage_pct" value="<?= e((string)$row['coverage_pct']) ?>"></div>
<div class="u-style-aae0403196"><label class="muted u-style-98847c28df"><?= e(t('common.shortage')) ?> <?= e(t('common.qty')) ?></label><input class="input" type="number" step="0.01" name="shortage_qty" value="<?= e((string)$row['shortage_qty']) ?>"></div>
<div class="u-style-aae0403196"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.auto_created')) ?></label><select name="auto_created"><option value="0" <?= ((int)$row['auto_created'] === 0) ? 'selected' : '' ?>><?= e(t('module.production_plans.no')) ?></option><option value="1" <?= ((int)$row['auto_created'] === 1) ? 'selected' : '' ?>><?= e(t('module.production_plans.yes')) ?></option></select></div>
<div class="u-style-9405df25bc"><label class="muted u-style-98847c28df"><?= e(t('module.production_plans.added_by')) ?></label><input class="input" name="added_by" value="<?= e((string)($row['added_by'] ?? '')) ?>" <?= $canEditAddedBy ? '' : 'readonly' ?>></div>
<div class="u-style-4ca11fcb42"><label class="muted u-style-98847c28df"><?= e(t('notes')) ?></label><textarea name="notes"><?= e((string)($row['notes'] ?? '')) ?></textarea></div>
<div class="row u-style-0466783d98"><button class="btn ok" type="submit" <?= $readOnlyAll ? 'disabled' : '' ?>><?= e(t('module.production_plans.update')) ?></button><a class="btn" href="/production-plans"><?= e(t('common.cancel')) ?></a></div>
</fieldset></form></div>
<?php if (!empty($approvalEvents)): ?><div class="card"><h3 class="u-style-d462248a40"><?= e(t('module.production_plans.governance_history')) ?></h3><div class="table-wrap"><table><thead><tr><th><?= e(t('module.production_plans.when')) ?></th><th><?= e(t('module.production_plans.action')) ?></th><th><?= e(t('module.production_plans.approval')) ?></th><th><?= e(t('module.production_plans.lock')) ?></th><th><?= e(t('common.reason')) ?></th><th><?= e(t('common.notes')) ?></th><th><?= e(t('module.production_plans.actor')) ?></th></tr></thead><tbody><?php foreach ($approvalEvents as $event): ?><tr><td><?= e((string)($event['acted_at'] ?? '')) ?></td><td><?= e((string)($event['action_name'] ?? '')) ?></td><td><?= e((string)($event['previous_approval_status'] ?? '-')) ?> -> <?= e((string)($event['new_approval_status'] ?? '-')) ?></td><td><?= ((int)($event['previous_locked_state'] ?? 0) === 1 ? e(t('module.production_plans.locked')) : e(t('module.production_plans.unlocked'))) ?> -> <?= ((int)($event['new_locked_state'] ?? 0) === 1 ? e(t('module.production_plans.locked')) : e(t('module.production_plans.unlocked'))) ?></td><td><?= e((string)($event['reason_text'] ?? '')) ?></td><td><?= e((string)($event['note_text'] ?? '')) ?></td><td><?= e((string)($event['actor_email'] ?? t('module.production_plans.system'))) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<?php if (!empty($activityTimeline)): ?><div class="card"><h3 class="u-style-d462248a40"><?= e(t('module.production_plans.activity_timeline')) ?></h3><div class="table-wrap"><table><thead><tr><th><?= e(t('module.production_plans.when')) ?></th><th><?= e(t('module.production_plans.action')) ?></th><th><?= e(t('module.production_plans.type')) ?></th><th><?= e(t('module.production_plans.state')) ?></th><th><?= e(t('module.production_plans.reason_or_note')) ?></th><th><?= e(t('module.production_plans.changes')) ?></th><th><?= e(t('module.production_plans.actor')) ?></th></tr></thead><tbody><?php foreach ($activityTimeline as $event): ?><tr><td><?= e((string)($event['created_at'] ?? '')) ?></td><td><?= e((string)($event['action_name'] ?? '')) ?></td><td><?= e((string)($event['event_type'] ?? '')) ?></td><td><?= e((string)($event['old_state'] ?? '-')) ?> -> <?= e((string)($event['new_state'] ?? '-')) ?></td><td><?= e(trim((string)($event['reason_text'] ?? '')) !== '' ? (string)$event['reason_text'] : (string)($event['note_text'] ?? '')) ?></td><td><?php $diff = is_array($event['diff'] ?? null) ? $event['diff'] : []; ?><?php if (!empty($diff)): ?><?php $items = []; foreach ($diff as $d) { $items[] = (string)($d['field'] ?? '') . ': ' . (string)($d['old'] ?? '-') . ' -> ' . (string)($d['new'] ?? '-'); } ?><?= e(implode(' | ', $items)) ?><?php else: ?>-<?php endif; ?></td><td><?= e((string)($event['actor_label'] ?? t('module.production_plans.system'))) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-close.php'; ?>
