CREATE TABLE IF NOT EXISTS org_companies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_code VARCHAR(40) NOT NULL,
    company_name VARCHAR(190) NOT NULL,
    legal_name VARCHAR(190) NULL,
    registration_no VARCHAR(120) NULL,
    tax_no VARCHAR(120) NULL,
    base_currency VARCHAR(16) NOT NULL DEFAULT 'JPY',
    timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Tokyo',
    email VARCHAR(190) NULL,
    phone VARCHAR(60) NULL,
    website VARCHAR(190) NULL,
    address_line_1 VARCHAR(190) NULL,
    address_line_2 VARCHAR(190) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(120) NULL,
    postal_code VARCHAR(40) NULL,
    country VARCHAR(120) NULL,
    logo_path VARCHAR(255) NULL,
    short_brand_name VARCHAR(120) NULL,
    report_header_text VARCHAR(255) NULL,
    report_footer_text VARCHAR(255) NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_org_companies_code (company_code),
    KEY idx_org_companies_primary (is_primary),
    KEY idx_org_companies_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS org_branches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    branch_code VARCHAR(40) NOT NULL,
    branch_name VARCHAR(190) NOT NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(60) NULL,
    address_line_1 VARCHAR(190) NULL,
    address_line_2 VARCHAR(190) NULL,
    city VARCHAR(120) NULL,
    state VARCHAR(120) NULL,
    postal_code VARCHAR(40) NULL,
    country VARCHAR(120) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_org_branches_company_code (company_id, branch_code),
    KEY idx_org_branches_company (company_id),
    KEY idx_org_branches_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS org_fiscal_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    fiscal_year_start CHAR(5) NULL,
    fiscal_year_end CHAR(5) NULL,
    default_tax_mode VARCHAR(32) NOT NULL DEFAULT 'exclusive',
    invoice_prefix VARCHAR(40) NULL,
    document_prefix_pattern VARCHAR(120) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_org_fiscal_company (company_id),
    KEY idx_org_fiscal_company (company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
