<?php
return [
    'tool_key' => 'css_token_editor',
    'key' => 'css_token_editor',
    'label' => 'CSS Token Editor',
    'name' => 'CSS Token Editor',
    'name_key' => 'studio.tool.css_token_editor.name',
    'description_key' => 'studio.tool.css_token_editor.description',
    'category' => 'authoring',
    'home_group' => 'design_content',
    'canonical_route' => '/apps/studio/tools/customization-studio/design-system/tokens',
    'placeholder' => false,
    'risk_level' => 'low',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.tools.css_token_editor.use', 'studio.tools.css_token_editor.mutate'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/customization-studio/design-system/tokens',
        '/apps/studio/tools/customization-studio/design-system/tokens/preview',
        '/apps/studio/tools/customization-studio/design-system/tokens/verify',
        '/apps/studio/tools/customization-studio/design-system/tokens/save',
        '/apps/studio/tools/customization-studio/design-system/tokens/source-snapshot',
    ],
    'views' => [
        'apps/Studio/Tools/CustomizationStudio/DesignSystem/DesignTokenEditor/Views/preview.php',
        'apps/Studio/Tools/CustomizationStudio/DesignSystem/DesignTokenEditor/Views/live_preview.php',
        'apps/Studio/Tools/CustomizationStudio/DesignSystem/DesignTokenEditor/Views/partials/live_preview.php',
    ],
    'services' => [
        'Apps\\Studio\\Controllers\\StudioController::cssTokenEditorPreview',
        'Apps\\Studio\\Controllers\\StudioController::cssTokenEditorLivePreview',
        'Apps\\Studio\\Controllers\\StudioController::cssTokenEditorVerify',
        'Apps\\Studio\\Controllers\\StudioController::cssTokenEditorSave',
        'Apps\\Studio\\Controllers\\StudioController::cssTokenEditorSourceSnapshot',
        'Apps\\Studio\\Tools\\CustomizationStudio\\DesignSystem\\DesignTokenEditor\\Services\\CssTokenEditorSaveService::save',
    ],
    'owner' => 'studio',
    'status' => 'governed_draft',
    'can_load' => ['theme'],
    'can_modify' => true,
    'requires_approval' => false,
    'writes_to_owner_artifact' => true,
    'supports_diff' => false,
    'supports_snapshot' => true,
    'supports_rollback' => false,
];
