<?php
declare(strict_types=1);

/**
 * Action Layer v1 definitions.
 *
 * Schema:
 * - key
 * - label_key
 * - module_key
 * - domain
 * - owner_plugin
 * - source_signal
 * - action_type
 * - target_url
 * - method (link|post|modal|future)
 * - priority (critical|high|normal|secondary)
 * - visible_if
 * - enabled_if
 * - status
 * - requires_confirmation
 * - is_placeholder
 * - attach_to (widget|coverage_zone|coverage_state)
 * - target (widget key OR coverage state key)
 */
return [
    [
        'key' => 'action.core.open_my_work',
        'label_key' => 'action.open_my_work',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.my_work',
        'action_type' => 'navigate',
        'target_url' => '/',
        'method' => 'link',
        'priority' => 'high',
            'product_id' => '{product_id}',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.my_work',
    ],
    [
        'key' => 'action.core.review_alerts',
        'label_key' => 'action.review_alerts',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.alerts',
        'action_type' => 'navigate',
        'target_url' => '/ops/notifications',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'logged_in',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.alerts',
    ],
    [
        'key' => 'action.core.open_approval_inbox',
        'label_key' => 'action.open_approval_inbox',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.approval_inbox',
        'action_type' => 'navigate',
        'target_url' => '/ops/approval-inbox',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'role_governance',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.approval_inbox',
    ],
    // Admin System Links: attach multiple admin/system links inside the widget card
    [
        'key' => 'action.core.admin_system.platform_dashboard',
        'label_key' => 'admin.launcher.title',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/admin',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.admin_system.access_control',
        'label_key' => 'action.access_control',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/ops/access-control',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.admin_system.user_dashboard',
        'label_key' => 'action.user_dashboard',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/ops/user-dashboard',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.admin_system.audit_log',
        'label_key' => 'action.audit_log',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'AdminTools',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/ops/audit-log',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.admin_system.admin_apps',
        'label_key' => 'dashboard.admin_apps',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'AdminTools',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/admin/apps',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.admin_system.admin_routes',
        'label_key' => 'dashboard.admin_routes',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'AdminTools',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/admin/routes',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.admin_system.admin_base',
        'label_key' => 'dashboard.admin_base',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.admin_system_links',
        'action_type' => 'navigate',
        'target_url' => '/admin/base',
        'method' => 'link',
        'priority' => 'normal',
        'enabled_if' => 'route_exists',
        'visible_if' => 'role_platform_admin_or_sysadmin',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_system_links',
    ],
    [
        'key' => 'action.core.approval_inbox.open_my_work',
        'label_key' => 'action.open_my_work',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.approval_inbox',
        'action_type' => 'navigate',
        'target_url' => '/',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'role_governance',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.approval_inbox',
    ],
    [
        'key' => 'action.core.approval_inbox.open_handoff',
        'label_key' => 'nav.cross_role_handoff',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.approval_inbox',
        'action_type' => 'navigate',
        'target_url' => '/apps/manufacturing/handoffs',
        'method' => 'link',
        'priority' => 'secondary',
        'visible_if' => 'role_governance',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.approval_inbox',
    ],
    [
        'key' => 'action.core.supervisor_cockpit.open_approval_inbox',
        'label_key' => 'action.open_approval_inbox',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.supervisor_cockpit',
        'action_type' => 'navigate',
        'target_url' => '/ops/approval-inbox',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'role_supervisor',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.supervisor_cockpit',
    ],
    [
        'key' => 'action.core.supervisor_cockpit.open_handoff',
        'label_key' => 'nav.cross_role_handoff',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.supervisor_cockpit',
        'action_type' => 'navigate',
        'target_url' => '/apps/manufacturing/handoffs',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'role_supervisor',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.supervisor_cockpit',
    ],
    [
        'key' => 'action.core.supervisor_cockpit.review_alerts',
        'label_key' => 'action.review_alerts',
        'module_key' => 'platform',
        'domain' => 'platform',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.supervisor_cockpit',
        'action_type' => 'navigate',
        'target_url' => '/ops/notifications',
        'method' => 'link',
        'priority' => 'secondary',
        'visible_if' => 'role_supervisor',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.supervisor_cockpit',
    ],
    [
        'key' => 'action.core.machine_leader_overview.open_my_work',
        'label_key' => 'action.open_my_work',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.machine_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/u/machines',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'role_machine_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.machine_leader_overview',
    ],
    [
        'key' => 'action.core.machine_leader_overview.open_approval_inbox',
        'label_key' => 'action.open_approval_inbox',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.machine_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/ops/approval-inbox?module=production_plan',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'role_machine_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.machine_leader_overview',
    ],
    [
        'key' => 'action.core.machine_leader_overview.open_handoff',
        'label_key' => 'nav.cross_role_handoff',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.machine_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/apps/manufacturing/handoffs',
        'method' => 'link',
        'priority' => 'secondary',
        'visible_if' => 'role_machine_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.machine_leader_overview',
    ],
    [
        'key' => 'action.core.qc_leader_overview.open_my_work',
        'label_key' => 'action.open_my_work',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.qc_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/u/qc',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'role_qc_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.qc_leader_overview',
    ],
    [
        'key' => 'action.core.qc_leader_overview.open_approval_inbox',
        'label_key' => 'action.open_approval_inbox',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.qc_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/ops/approval-inbox?module=qc_entry',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'role_qc_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.qc_leader_overview',
    ],
    [
        'key' => 'action.core.qc_leader_overview.open_handoff',
        'label_key' => 'nav.cross_role_handoff',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.qc_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/apps/manufacturing/handoffs',
        'method' => 'link',
        'priority' => 'secondary',
        'visible_if' => 'role_qc_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.qc_leader_overview',
    ],
    [
        'key' => 'action.core.dispatch_leader_overview.open_my_work',
        'label_key' => 'action.open_my_work',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.dispatch_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/u/dispatch',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'role_dispatch_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.dispatch_leader_overview',
    ],
    [
        'key' => 'action.core.dispatch_leader_overview.open_approval_inbox',
        'label_key' => 'action.open_approval_inbox',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.dispatch_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/ops/approval-inbox?module=dispatch_entry',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'role_dispatch_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.dispatch_leader_overview',
    ],
    [
        'key' => 'action.core.dispatch_leader_overview.open_handoff',
        'label_key' => 'nav.cross_role_handoff',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.dispatch_leader_overview',
        'action_type' => 'navigate',
        'target_url' => '/apps/manufacturing/handoffs',
        'method' => 'link',
        'priority' => 'secondary',
        'visible_if' => 'role_dispatch_leader',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.dispatch_leader_overview',
    ],
    [
        'key' => 'action.core.open_admin_tools',
        'label_key' => 'action.open_admin_tools',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'AdminTools',
        'source_signal' => 'core.admin_tools',
        'action_type' => 'navigate',
        'target_url' => '/admin/apps',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'admin_tools',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.admin_tools',
    ],
    [
        'key' => 'action.core.inspect_routes',
        'label_key' => 'action.inspect_routes',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'AdminTools',
        'source_signal' => 'core.routes',
        'action_type' => 'navigate',
        'target_url' => '/admin/routes',
        'method' => 'link',
        'priority' => 'secondary',
        'visible_if' => 'admin_tools',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.routes',
    ],
    [
        'key' => 'action.core.open_base_settings',
        'label_key' => 'action.open_base_settings',
        'module_key' => 'admin_tools',
        'domain' => 'admin',
        'owner_plugin' => 'Base',
        'source_signal' => 'core.base_builder',
        'action_type' => 'navigate',
        'target_url' => '/admin/base',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'can_access_base',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'core.base_builder',
    ],
    [
        'key' => 'action.mfg.open_orders.view_open_orders',
        'label_key' => 'action.view_open_orders',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'mfg.open_orders',
        'action_type' => 'drilldown',
        'target_url' => '/daily-orders',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.open_orders',
    ],
    [
        'key' => 'action.mfg.open_orders.review_shortages',
        'label_key' => 'action.review_shortages',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'mfg.open_orders',
        'action_type' => 'recovery',
        'target_url' => '/daily-orders?coverage=low',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.mfg.open_orders.shortage_triage',
        'workflow_type' => 'triage',
        'entry_intent' => 'Review low-coverage daily orders and prioritize recovery rows.',
        'target_mode' => 'list',
        'context_params' => [
            'coverage' => 'low',
        ],
        'source_state' => 'signal.open_orders',
        'safe_mode' => true,
        'attach_to' => 'widget',
        'target' => 'mfg.open_orders',
    ],
    [
        'key' => 'action.mfg.open_orders.open_plans',
        'label_key' => 'action.open_production_plans',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionPlans',
        'source_signal' => 'mfg.open_orders',
        'action_type' => 'planning',
        'target_url' => '/production-plans?status=Planned',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.mfg.open_orders.plan_backlog',
        'workflow_type' => 'planning',
        'entry_intent' => 'Open planned production backlog and convert to executable queue.',
        'target_mode' => 'list',
        'context_params' => [
            'status' => 'Planned',
        ],
        'source_state' => 'signal.open_orders',
        'safe_mode' => true,
        'attach_to' => 'widget',
        'target' => 'mfg.open_orders',
    ],

    [
        'key' => 'action.mfg.coverage.open_analysis',
        'label_key' => 'action.open_coverage_analysis',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'mfg.coverage_pct',
        'action_type' => 'analysis',
        'target_url' => '/manufacturing/coverage',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'logged_in',
        'enabled_if' => 'coverage_available',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.coverage_pct',
    ],
    [
        'key' => 'action.mfg.coverage.review_low_rows',
        'label_key' => 'action.review_low_coverage_rows',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'mfg.coverage_pct',
        'action_type' => 'recovery',
        'target_url' => '/daily-orders?coverage=low',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.coverage_pct',
    ],
    [
        'key' => 'action.mfg.coverage.jump_plans',
        'label_key' => 'action.jump_to_plans',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionPlans',
        'source_signal' => 'mfg.coverage_pct',
        'action_type' => 'planning',
        'target_url' => '/production-plans?status=Planned',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.coverage_pct',
    ],

    [
        'key' => 'action.mfg.shortage.review_orders',
        'label_key' => 'action.review_shortage_orders',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'mfg.shortage_qty',
        'action_type' => 'recovery',
        'target_url' => '/daily-orders?coverage=low',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.shortage_qty',
    ],
    [
        'key' => 'action.mfg.shortage.open_plans',
        'label_key' => 'action.open_production_plans',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionPlans',
        'source_signal' => 'mfg.shortage_qty',
        'action_type' => 'planning',
        'target_url' => '/production-plans?status=Planned',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.shortage_qty',
    ],
    [
        'key' => 'action.mfg.shortage.check_ledger',
        'label_key' => 'action.check_ledger',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Ledger',
        'source_signal' => 'mfg.shortage_qty',
        'action_type' => 'inventory',
        'target_url' => '/ledger',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.shortage_qty',
    ],

    [
        'key' => 'action.mfg.forecast.open_pre_orders',
        'label_key' => 'action.open_pre_orders',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'PreOrders',
        'source_signal' => 'mfg.forecast_pressure',
        'action_type' => 'planning',
        'target_url' => '/pre-orders',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.forecast_pressure',
    ],
    [
        'key' => 'action.mfg.forecast.compare_plans',
        'label_key' => 'action.compare_planned_supply',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionPlans',
        'source_signal' => 'mfg.forecast_pressure',
        'action_type' => 'planning',
        'target_url' => '/production-plans?status=Planned',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.forecast_pressure',
    ],
    [
        'key' => 'action.mfg.forecast.review_backlog',
        'label_key' => 'action.review_planning_backlog',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionQueue',
        'source_signal' => 'mfg.forecast_pressure',
        'action_type' => 'planning',
        'target_url' => '/manufacturing/production-queue',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.forecast_pressure',
    ],

    [
        'key' => 'action.mfg.dispatch.open_dispatch',
        'label_key' => 'action.open_dispatch_entries',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DispatchEntries',
        'source_signal' => 'mfg.ready_dispatch',
        'action_type' => 'dispatch',
        'target_url' => '/dispatch-entries/leader',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_dispatch',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.ready_dispatch',
    ],
    [
        'key' => 'action.mfg.dispatch.review_ready',
        'label_key' => 'action.review_ready_items',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DispatchEntries',
        'source_signal' => 'mfg.ready_dispatch',
        'action_type' => 'dispatch',
        'target_url' => '/dispatch-entries/leader',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'admin_or_dispatch',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.mfg.dispatch.ready_review',
        'workflow_type' => 'dispatch',
        'entry_intent' => 'Review ready dispatch entries and clear outbound bottlenecks.',
        'target_mode' => 'list',
        'source_state' => 'signal.dispatch_ready',
        'safe_mode' => true,
        'attach_to' => 'widget',
        'target' => 'mfg.ready_dispatch',
    ],
    [
        'key' => 'action.mfg.dispatch.validate_qc',
        'label_key' => 'action.validate_qc_completion',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'QCEntries',
        'source_signal' => 'mfg.ready_dispatch',
        'action_type' => 'quality',
        'target_url' => '/ops/approval-inbox?module=qc_entry',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'admin_or_dispatch',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.ready_dispatch',
    ],

    [
        'key' => 'action.mfg.qc.open_qc_entries',
        'label_key' => 'action.open_qc_entries',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'QCEntries',
        'source_signal' => 'mfg.qc_pressure',
        'action_type' => 'quality',
        'target_url' => '/qc-entries/leader',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_qc',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.qc_pressure',
    ],
    [
        'key' => 'action.mfg.qc.open_qc_plans',
        'label_key' => 'action.open_qc_plans',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'QCPlans',
        'source_signal' => 'mfg.qc_pressure',
        'action_type' => 'quality',
        'target_url' => '/qc-plans',
        'method' => 'link',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'widget',
        'target' => 'mfg.qc_pressure',
    ],
    [
        'key' => 'action.mfg.qc.review_pending_checks',
        'label_key' => 'action.review_pending_checks',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'QCEntries',
        'source_signal' => 'mfg.qc_pressure',
        'action_type' => 'quality',
        'target_url' => '/qc-entries/leader',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_qc',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.mfg.qc.pending_checks',
        'workflow_type' => 'quality',
        'entry_intent' => 'Review open QC checks and unblock downstream dispatch.',
        'target_mode' => 'list',
        'context_params' => [
            'status' => 'Open',
        ],
        'source_state' => 'signal.qc_pressure',
        'safe_mode' => true,
        'attach_to' => 'widget',
        'target' => 'mfg.qc_pressure',
    ],

    [
        'key' => 'action.coverage.review_shortages',
        'label_key' => 'action.review_shortages',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'coverage.zone',
        'action_type' => 'recovery',
        'target_url' => '/daily-orders?coverage=low',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'coverage_zone',
        'target' => 'global',
    ],
    [
        'key' => 'action.coverage.open_queue',
        'label_key' => 'action.open_production_queue',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionQueue',
        'source_signal' => 'coverage.zone',
        'action_type' => 'planning',
        'target_url' => '/manufacturing/production-queue',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'attach_to' => 'coverage_zone',
        'target' => 'global',
    ],
    [
        'key' => 'action.coverage.recalc',
        'label_key' => 'action.recalculate_coverage',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Base',
        'source_signal' => 'coverage.zone',
        'action_type' => 'refresh',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'secondary',
        'visible_if' => 'admin_tools',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => true,
        'is_placeholder' => true,
        'attach_to' => 'coverage_zone',
        'target' => 'global',
    ],

    [
        'key' => 'action.coverage.low.plan_recovery',
        'label_key' => 'action.start_plan_draft',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionPlans',
        'source_signal' => 'coverage.row.low',
        'action_type' => 'recovery',
        'target_url' => '/production-plans/start-draft',
        'method' => 'post',
        'priority' => 'critical',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => true,
        'confirmation_message' => 'Create a draft production plan for this shortage row?',
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.low.recovery_plan',
        'workflow_type' => 'transaction_start',
        'entry_intent' => 'Create a focused draft production plan for the shortage row and continue in edit mode.',
        'target_mode' => 'draft',
        'transaction_type' => 'create_draft',
        'transaction_target' => 'production_plan',
        'create_mode' => 'explicit_post',
        'draft_mode' => 'edit_after_create',
        'transaction_payload' => [
            'product_id' => '{product_id}',
            'daily_order_id' => '{daily_order_id}',
            'required_date' => '{required_date}',
            'shortage_qty' => '{shortage_qty}',
            'plan_type' => 'Recovery',
            'reference_doctype' => 'DailyOrder',
            'reference_name' => '{order_id}',
            'failure_fallback' => '/manufacturing/coverage',
        ],
        'audit_action' => 'coverage.low.plan_recovery_draft',
        'success_redirect' => '/production-plans/edit',
        'failure_fallback' => '/manufacturing/coverage',
        'transaction_safe_mode' => true,
        'source_state' => 'coverage.low',
        'requires_record_context' => true,
        'empty_state_fallback' => '/production-plans',
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'low',
    ],
    [
        'key' => 'action.coverage.low.ledger',
        'label_key' => 'action.check_ledger',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Ledger',
        'source_signal' => 'coverage.row.low',
        'action_type' => 'inventory',
        'target_url' => '/ledger?product_id={product_id}',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.low.stock_investigation',
        'workflow_type' => 'analysis',
        'entry_intent' => 'Inspect product-level ledger movements for shortage diagnosis.',
        'target_mode' => 'list',
        'context_params' => [
            'product_id' => '{product_id}',
        ],
        'source_state' => 'coverage.low',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'low',
    ],
    [
        'key' => 'action.coverage.partial.balance_supply',
        'label_key' => 'action.balance_supply',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionQueue',
        'source_signal' => 'coverage.row.partial',
        'action_type' => 'planning',
        'target_url' => '/manufacturing/production-queue',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.partial.balance_queue',
        'workflow_type' => 'queue_review',
        'entry_intent' => 'Review queue for the target date and rebalance partial coverage.',
        'target_mode' => 'board',
        'context_params' => [
            'date' => '{required_date}',
        ],
        'source_state' => 'coverage.partial',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.partial.review_plans',
        'label_key' => 'action.start_plan_adjustment_draft',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'ProductionPlans',
        'source_signal' => 'coverage.row.partial',
        'action_type' => 'planning',
        'target_url' => '/production-plans/start-draft',
        'method' => 'post',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => true,
        'confirmation_message' => 'Create a draft adjustment plan for this partial-coverage row?',
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.partial.plan_adjustment',
        'workflow_type' => 'transaction_start',
        'entry_intent' => 'Create a balancing draft plan to close the remaining coverage gap and continue in edit mode.',
        'target_mode' => 'draft',
        'transaction_type' => 'create_draft',
        'transaction_target' => 'production_plan',
        'create_mode' => 'explicit_post',
        'draft_mode' => 'edit_after_create',
        'transaction_payload' => [
            'product_id' => '{product_id}',
            'daily_order_id' => '{daily_order_id}',
            'required_date' => '{required_date}',
            'shortage_qty' => '{shortage_qty}',
            'plan_type' => 'Adjustment',
            'reference_doctype' => 'DailyOrder',
            'reference_name' => '{order_id}',
            'failure_fallback' => '/manufacturing/coverage',
        ],
        'audit_action' => 'coverage.partial.plan_adjustment_draft',
        'success_redirect' => '/production-plans/edit',
        'failure_fallback' => '/manufacturing/coverage',
        'transaction_safe_mode' => true,
        'source_state' => 'coverage.partial',
        'requires_record_context' => true,
        'empty_state_fallback' => '/production-plans',
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.full.dispatch_ready',
        'label_key' => 'action.start_dispatch_draft',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DispatchEntries',
        'source_signal' => 'coverage.row.full',
        'action_type' => 'dispatch',
        'target_url' => '/dispatch-entries/start-draft',
        'method' => 'post',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => true,
        'confirmation_message' => 'Create a draft dispatch entry for this fully covered row?',
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.full.dispatch_entry',
        'workflow_type' => 'transaction_start',
        'entry_intent' => 'Create a draft dispatch entry from this covered row and continue in edit mode.',
        'target_mode' => 'draft',
        'transaction_type' => 'create_draft',
        'transaction_target' => 'dispatch_entry',
        'create_mode' => 'explicit_post',
        'draft_mode' => 'edit_after_create',
        'transaction_payload' => [
            'product_id' => '{product_id}',
            'daily_order_id' => '{order_id}',
            'required_date' => '{required_date}',
            'covered_qty' => '{covered_qty}',
            'customer_name' => '{customer_name}',
            'failure_fallback' => '/manufacturing/coverage',
        ],
        'audit_action' => 'coverage.full.dispatch_draft',
        'success_redirect' => '/dispatch-entries/edit',
        'failure_fallback' => '/manufacturing/coverage',
        'transaction_safe_mode' => true,
        'source_state' => 'coverage.full',
        'requires_record_context' => true,
        'empty_state_fallback' => '/dispatch-entries',
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'full',
    ],
    [
        'key' => 'action.coverage.full.validate_qc',
        'label_key' => 'action.start_qc_draft',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'QCEntries',
        'source_signal' => 'coverage.row.full',
        'action_type' => 'quality',
        'target_url' => '/qc-entries/start-draft',
        'method' => 'post',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => true,
        'confirmation_message' => 'Create a draft QC entry for this covered row?',
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.full.qc_gate',
        'workflow_type' => 'transaction_start',
        'entry_intent' => 'Create a draft QC entry for final gate validation and continue in edit mode.',
        'target_mode' => 'draft',
        'transaction_type' => 'create_draft',
        'transaction_target' => 'qc_entry',
        'create_mode' => 'explicit_post',
        'draft_mode' => 'edit_after_create',
        'transaction_payload' => [
            'product_id' => '{product_id}',
            'daily_order_id' => '{order_id}',
            'required_date' => '{required_date}',
            'covered_qty' => '{covered_qty}',
            'qc_type' => 'Final',
            'failure_fallback' => '/manufacturing/coverage',
        ],
        'audit_action' => 'coverage.full.qc_draft',
        'success_redirect' => '/qc-entries/edit',
        'failure_fallback' => '/manufacturing/coverage',
        'transaction_safe_mode' => true,
        'source_state' => 'coverage.full',
        'requires_record_context' => true,
        'empty_state_fallback' => '/qc-entries',
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'full',
    ],
    [
        'key' => 'action.coverage.third_party.stock_check',
        'label_key' => 'action.check_stock_position',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Ledger',
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'inventory',
        'target_url' => '/ledger?product_id={product_id}',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.third_party.stock_check',
        'workflow_type' => 'inventory',
        'entry_intent' => 'Check current product stock position before escalating shortage handling.',
        'target_mode' => 'list',
        'context_params' => [
            'product_id' => '{product_id}',
        ],
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'low',
    ],
    [
        'key' => 'action.coverage.third_party.review_supplier',
        'label_key' => 'action.review_supplier_inbound',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Products',
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'supplier',
        'target_url' => '/products/360?id={product_id}',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_ops',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.third_party.supplier_review',
        'workflow_type' => 'supplier_review',
        'entry_intent' => 'Review supplier/inbound context from Part 360 before deciding next move.',
        'target_mode' => 'details',
        'context_params' => [
            'id' => '{product_id}',
        ],
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'low',
    ],
    [
        'key' => 'action.coverage.third_party.procurement_review',
        'label_key' => 'action.procurement_review_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'procurement',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'workflow_key' => 'wf.coverage.third_party.procurement_review',
        'workflow_type' => 'procurement',
        'entry_intent' => 'Planned procurement/inbound workflow for third-party shortages.',
        'target_mode' => 'planned',
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'low',
    ],
    [
        'key' => 'action.coverage.third_party.review_demand',
        'label_key' => 'action.review_demand_record',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'drilldown',
        'target_url' => '/daily-orders/360?id={order_id}',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_ops',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.third_party.demand_review',
        'workflow_type' => 'demand_review',
        'entry_intent' => 'Review the demand order before supplier-side fulfillment decisions.',
        'target_mode' => 'details',
        'context_params' => [
            'id' => '{order_id}',
        ],
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'low',
    ],
    [
        'key' => 'action.coverage.direct.review_demand',
        'label_key' => 'action.review_demand_record',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'coverage.row.direct_supplier',
        'action_type' => 'drilldown',
        'target_url' => '/daily-orders/360?id={order_id}',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_or_ops',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.direct_supplier.demand_review',
        'workflow_type' => 'demand_review',
        'entry_intent' => 'Review demand details for direct-supplier fulfillment follow-through.',
        'target_mode' => 'details',
        'context_params' => [
            'id' => '{order_id}',
        ],
        'source_state' => 'coverage.direct_supplier',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'full',
    ],
    [
        'key' => 'action.coverage.direct.supplier_fulfillment_review',
        'label_key' => 'action.supplier_fulfillment_review_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'coverage.row.direct_supplier',
        'action_type' => 'supplier',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'workflow_key' => 'wf.coverage.direct_supplier.fulfillment_review',
        'workflow_type' => 'supplier_fulfillment',
        'entry_intent' => 'Planned supplier fulfillment review workflow (direct supplier path).',
        'target_mode' => 'planned',
        'source_state' => 'coverage.direct_supplier',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'full',
    ],
    [
        'key' => 'action.coverage.direct.delivery_tracking',
        'label_key' => 'action.direct_delivery_tracking_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'coverage.row.direct_supplier',
        'action_type' => 'tracking',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'workflow_key' => 'wf.coverage.direct_supplier.delivery_tracking',
        'workflow_type' => 'delivery_tracking',
        'entry_intent' => 'Planned direct-delivery tracking workflow for supplier shipments.',
        'target_mode' => 'planned',
        'source_state' => 'coverage.direct_supplier',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'full',
    ],
    [
        'key' => 'action.coverage.third_party.stock_check.partial',
        'label_key' => 'action.check_stock_position',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Ledger',
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'inventory',
        'target_url' => '/ledger?product_id={product_id}',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.third_party.stock_check.partial',
        'workflow_type' => 'inventory',
        'entry_intent' => 'Check stock position before escalating partial third-party gap.',
        'target_mode' => 'list',
        'context_params' => [
            'product_id' => '{product_id}',
        ],
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.third_party.review_supplier.partial',
        'label_key' => 'action.review_supplier_inbound',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'Products',
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'supplier',
        'target_url' => '/products/360?id={product_id}',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_ops',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.third_party.supplier_review.partial',
        'workflow_type' => 'supplier_review',
        'entry_intent' => 'Review supplier/inbound context for partially covered third-party demand.',
        'target_mode' => 'details',
        'context_params' => [
            'id' => '{product_id}',
        ],
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.third_party.procurement_review.partial',
        'label_key' => 'action.procurement_review_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'procurement',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'workflow_key' => 'wf.coverage.third_party.procurement_review.partial',
        'workflow_type' => 'procurement',
        'entry_intent' => 'Planned procurement/inbound workflow for partial third-party shortages.',
        'target_mode' => 'planned',
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.third_party.review_demand.partial',
        'label_key' => 'action.review_demand_record',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'coverage.row.third_party',
        'action_type' => 'drilldown',
        'target_url' => '/daily-orders/360?id={order_id}',
        'method' => 'link',
        'priority' => 'high',
        'visible_if' => 'admin_or_ops',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.third_party.demand_review.partial',
        'workflow_type' => 'demand_review',
        'entry_intent' => 'Review demand details for partial third-party coverage gap.',
        'target_mode' => 'details',
        'context_params' => [
            'id' => '{order_id}',
        ],
        'source_state' => 'coverage.third_party',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.direct.review_demand.partial',
        'label_key' => 'action.review_demand_record',
        'module_key' => 'manufacturing_ipm',
        'domain' => 'manufacturing',
        'owner_plugin' => 'DailyOrders',
        'source_signal' => 'coverage.row.direct_supplier',
        'action_type' => 'drilldown',
        'target_url' => '/daily-orders/360?id={order_id}',
        'method' => 'link',
        'priority' => 'critical',
        'visible_if' => 'admin_or_ops',
        'enabled_if' => 'route_exists',
        'status' => 'active',
        'requires_confirmation' => false,
        'is_placeholder' => false,
        'workflow_key' => 'wf.coverage.direct_supplier.demand_review.partial',
        'workflow_type' => 'demand_review',
        'entry_intent' => 'Review demand details for partial direct-supplier fulfillment.',
        'target_mode' => 'details',
        'context_params' => [
            'id' => '{order_id}',
        ],
        'source_state' => 'coverage.direct_supplier',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.direct.supplier_fulfillment_review.partial',
        'label_key' => 'action.supplier_fulfillment_review_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'coverage.row.direct_supplier',
        'action_type' => 'supplier',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'high',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'workflow_key' => 'wf.coverage.direct_supplier.fulfillment_review.partial',
        'workflow_type' => 'supplier_fulfillment',
        'entry_intent' => 'Planned supplier fulfillment review for partial direct-supplier rows.',
        'target_mode' => 'planned',
        'source_state' => 'coverage.direct_supplier',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],
    [
        'key' => 'action.coverage.direct.delivery_tracking.partial',
        'label_key' => 'action.direct_delivery_tracking_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'coverage.row.direct_supplier',
        'action_type' => 'tracking',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'normal',
        'visible_if' => 'admin_strict',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'workflow_key' => 'wf.coverage.direct_supplier.delivery_tracking.partial',
        'workflow_type' => 'delivery_tracking',
        'entry_intent' => 'Planned direct delivery tracking for partial direct-supplier rows.',
        'target_mode' => 'planned',
        'source_state' => 'coverage.direct_supplier',
        'requires_record_context' => true,
        'safe_mode' => true,
        'attach_to' => 'coverage_state',
        'target' => 'partial',
    ],

    [
        'key' => 'action.ext.procurement.placeholder',
        'label_key' => 'action.procurement_placeholder',
        'module_key' => 'procurement',
        'domain' => 'extension',
        'owner_plugin' => null,
        'source_signal' => 'extensions.zone',
        'action_type' => 'future',
        'target_url' => '',
        'method' => 'future',
        'priority' => 'secondary',
        'visible_if' => 'admin_tools',
        'enabled_if' => 'never',
        'status' => 'planned',
        'requires_confirmation' => false,
        'is_placeholder' => true,
        'attach_to' => 'coverage_zone',
        'target' => 'extensions',
    ],
];
