<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-open.php'; ?>
<div class="card"><div class="row u-style-2d7d2729a4"><h2 class="u-style-1169661891"><?= e(t('add_pre_order')) ?></h2><a class="btn" href="/pre-orders"><?= e(t('back_to_list')) ?></a></div></div>
<?php if (!empty($error ?? '')): ?><div class="card u-style-64e7e2c551"><?= e((string)$error) ?></div><?php endif; ?>
<div class="card"><form method="post" action="/pre-orders/add" class="row"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>">
<div class="u-style-7b1dd1f4df"><label class="muted u-style-98847c28df"><?= e(t('forecast_type')) ?> *</label><input class="input" name="forecast_type" required value="<?= e((string)($old['forecast_type'] ?? '')) ?>"></div>
<div class="u-style-2f7ab6d1f3"><label class="muted u-style-98847c28df"><?= e(t('planning_priority')) ?></label><select name="planning_priority"><option value="Critical" <?= ((string)($old['planning_priority'] ?? 'Normal') === 'Critical') ? 'selected' : '' ?>>Critical</option><option value="High" <?= ((string)($old['planning_priority'] ?? 'Normal') === 'High') ? 'selected' : '' ?>>High</option><option value="Medium" <?= ((string)($old['planning_priority'] ?? 'Normal') === 'Medium') ? 'selected' : '' ?>>Medium</option><option value="Normal" <?= ((string)($old['planning_priority'] ?? 'Normal') === 'Normal') ? 'selected' : '' ?>>Normal</option><option value="Low" <?= ((string)($old['planning_priority'] ?? 'Normal') === 'Low') ? 'selected' : '' ?>>Low</option></select></div>
<div class="u-style-35f3431aa2"><label class="muted u-style-98847c28df"><?= e(t('part')) ?> *</label><select name="product_id" required><option value=""><?= e(t('select_part')) ?></option><?php foreach ($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= ((int)($old['product_id'] ?? 0) === (int)$p['id']) ? 'selected' : '' ?>><?= e((string)$p['parts_name']) ?> (<?= e((string)$p['parts_number']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-eb62184e30"><label class="muted u-style-98847c28df">Planned Qty *</label><input class="input" type="number" step="0.01" name="planned_qty" required value="<?= e((string)($old['planned_qty'] ?? '')) ?>"></div>
<div class="u-style-eb62184e30"><label class="muted u-style-98847c28df">Balance Qty</label><input class="input" type="number" step="0.01" name="balance_qty" value="<?= e((string)($old['balance_qty'] ?? '0')) ?>"></div>
<div class="u-style-2f7ab6d1f3"><label class="muted u-style-98847c28df">Required Date</label><input class="input" type="date" name="required_date" value="<?= e((string)($old['required_date'] ?? '')) ?>"></div>
<div class="u-style-4ca11fcb42"><label class="muted u-style-98847c28df"><?= e(t('notes')) ?></label><textarea name="notes"><?= e((string)($old['notes'] ?? '')) ?></textarea></div>
<div class="row u-style-0466783d98"><button class="btn ok" type="submit"><?= e(t('save_pre_order')) ?></button><a class="btn" href="/pre-orders"><?= e(t('cancel')) ?></a></div>
</form></div>
<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-close.php'; ?>
