<?php
return [
    'key' => 'resource_explorer',
    'name' => 'Resource Explorer',
    'name_key' => 'studio.tool.resource_explorer.name',
    'description_key' => 'studio.tool.resource_explorer.description',
    'category' => 'discovery',
    'home_group' => 'governance',
    'status' => 'available',
    'canonical_route' => '/apps/studio/library',
    'placeholder' => false,
    'risk_level' => 'read_only',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.view'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/library', '/apps/studio/tools/resource-explorer'],
    'views' => ['apps/Studio/Views/partials/library_explorer.php'],
    'services' => ['Apps\\Studio\\Services\\AppStudioRegistryService'],
    'owner' => 'studio',
    'can_load' => ['app', 'module', 'view', 'dashboard', 'route', 'nav'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => false,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
