<?php
return [
    // Instance-level Studio tool availability policy.
    // Only enabled tools can be entered through route dispatch.
    'studio_tools' => [
        'view_editor' => 'enabled',
        'menu_editor' => 'enabled',
        'theme_tool' => 'enabled',
        'customization_studio' => 'enabled',
        'app_builder' => 'enabled',
        'module_builder' => 'enabled',
        'plugin_builder' => 'enabled',
        'package_tool' => 'enabled',
        'route_designer' => 'enabled',
        'nav_menu_tool' => 'enabled',
        'widget_builder' => 'enabled',
        'form_builder' => 'enabled',
        'workflow_designer' => 'enabled',
        'rule_designer' => 'enabled',
        'integration_designer' => 'enabled',
        'import_export_mapper' => 'enabled',
        'notification_template_designer' => 'enabled',
        'permission_profile_tool' => 'enabled',
        'change_control_center' => 'enabled',
        'css_selector_tool' => 'enabled',
        'css_live_editor' => 'enabled',
        'report_designer' => 'enabled',
        'label_designer' => 'enabled',
        'db_schema_tool' => 'enabled',
        'localization_studio' => 'enabled',
        'css_token_editor' => 'enabled',
        'resource_explorer' => 'enabled',
        'localization_scan_extraction' => 'enabled',
        'validation_center' => 'enabled',
        'audit_history' => 'enabled',
        'token_impact_explorer' => 'enabled',
        'style_compliance' => 'enabled',
    ],
];
