CREATE TABLE IF NOT EXISTS handoff_tracking (
    id INT AUTO_INCREMENT PRIMARY KEY,
    entity_type VARCHAR(40) NOT NULL,
    entity_id INT NOT NULL,
    stage VARCHAR(50) NOT NULL,
    owner_role VARCHAR(80) NULL,
    owner_user_id INT NULL,
    owner_display VARCHAR(190) NULL,
    owner_assigned_at DATETIME NULL,
    entered_stage_at DATETIME NULL,
    ready_since DATETIME NULL,
    blocked_since DATETIME NULL,
    released_since DATETIME NULL,
    escalation_level VARCHAR(10) NULL,
    escalation_state VARCHAR(80) NULL,
    escalated_at DATETIME NULL,
    notes TEXT NULL,
    updated_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_handoff_target (entity_type, entity_id, stage),
    KEY idx_handoff_stage (stage),
    KEY idx_handoff_owner_role (owner_role),
    KEY idx_handoff_escalated_at (escalated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
