<?php
return [
    'key' => 'css_selector_tool',
    'name' => 'CSS Selector Tool',
    'name_key' => 'studio.tool.css_selector_tool.name',
    'description_key' => 'studio.tool.css_selector_tool.description',
    'category' => 'authoring',
    'home_group' => 'design_content',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/customization-studio/diagnose/css-selector-inspector',
    'placeholder' => true,
    'risk_level' => 'medium',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/customization-studio/diagnose/css-selector-inspector'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['view', 'component', 'theme'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => false,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
