<?php
return [
    'key' => 'permission_profile_tool',
    'name' => 'Permission Profile Tool',
    'name_key' => 'studio.tool.permission_profile_tool.name',
    'description_key' => 'studio.tool.permission_profile_tool.description',
    'category' => 'governance',
    'home_group' => 'governance',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/permission-profile-tool',
    'placeholder' => true,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/permission-profile-tool'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'migration' => [
        'status' => 'scope_corrected',
        'message_key' => 'studio.migration.permission_profile_tool',
        'note' => 'Studio may compose permission declarations and experience profiles but cannot grant authorization.',
    ],
    'can_load' => ['permission_profile', 'app', 'module'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
