<?php
return [
    'tool_key' => 'localization_studio',
    'key' => 'localization_studio',
    'label' => 'Localization Studio',
    'name' => 'Localization Studio',
    'name_key' => 'studio.tool.localization_studio.name',
    'description_key' => 'studio.tool.localization_studio.description',
    'category' => 'inspection',
    'home_group' => 'design_content',
    'canonical_route' => '/apps/studio/tools/localization-studio',
    'placeholder' => false,
    'risk_level' => 'low',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.tools.localization_studio.use'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => [
        '/apps/studio/tools/localization-studio',
        '/apps/studio/tools/localization-studio/edit',
        '/apps/studio/tools/localization-studio/edit/save',
    ],
    'views' => [
        'apps/Studio/Tools/LocalizationStudio/Views/preview.php',
        'apps/Studio/Tools/LocalizationStudio/Views/editor.php',
    ],
    'services' => [
        'Apps\\Studio\\Tools\\LocalizationStudio\\Services\\LocalizationStudioDiscoveryService::scan',
        'Apps\\Studio\\Tools\\LocalizationStudio\\Services\\LocalizationStudioEditService',
    ],
    'owner' => 'studio',
    'status' => 'active',
    'can_load' => [],
    'can_modify' => true,
    'requires_approval' => false,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
