<?php
return [
    'tool_key' => 'theme_tool',
    'key' => 'theme_tool',
    'label' => 'Theme Doctor',
    'name' => 'Theme Doctor',
    'name_key' => 'studio.tool.theme_tool.name',
    'description_key' => 'studio.tool.theme_tool.description',
    'category' => 'diagnostics',
    'home_group' => 'governance',
    'canonical_route' => '/apps/studio/tools/customization-studio/diagnose/theme-doctor',
    'placeholder' => false,
    'risk_level' => 'low',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.tools.theme_tool.use'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/customization-studio/diagnose/theme-doctor'],
    'views' => ['apps/Studio/Tools/CustomizationStudio/Diagnose/ThemeDoctor/Views/preview.php'],
    'services' => [
        'Apps\\Studio\\Controllers\\StudioController::themeToolPreview',
    ],
    'owner' => 'studio',
    'status' => 'readonly_diagnostic',
    'can_load' => ['theme', 'view', 'dashboard', 'surface'],
    'can_modify' => false,
    'requires_approval' => false,
    'writes_to_owner_artifact' => false,
    'supports_diff' => false,
    'supports_snapshot' => false,
    'supports_rollback' => false,
];
