<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'sbaio',
    'items' => [
        // SBAIO app surfaces intentionally remain untagged in the sidebar contract.
        // They sit outside the current manufacturing/ops lane vocabulary used by
        // SidebarBuilder module restrictions.
        [
            'source_key' => 'apps.sbaio.dashboard',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_home',
            'feature_key' => 'sbaio_dashboard',
            'label_key' => 'nav.sbaio_dashboard',
            'label' => 'SBAIO Workspace',
            'url' => '/apps/sbaio',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 10,
            'priority' => 100,
            'always_visible' => true,
        ],
        [
            'source_key' => 'apps.sbaio.reports',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_reports',
            'feature_key' => 'sbaio_reports',
            'label_key' => 'nav.sbaio_reports',
            'label' => 'Analytics',
            'url' => '/apps/sbaio/reports',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 15,
            'priority' => 82,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_staff',
            'feature_key' => 'staff',
            'label_key' => 'nav.sbaio_staff',
            'label' => 'Staff',
            'url' => '/apps/sbaio/staff',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 20,
            'priority' => 78,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_attendance',
            'feature_key' => 'attendance',
            'label_key' => 'nav.sbaio_attendance',
            'label' => 'Attendance',
            'url' => '/apps/sbaio/attendance',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 30,
            'priority' => 76,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_timecards',
            'feature_key' => 'timecards',
            'label_key' => 'nav.sbaio_timecards',
            'label' => 'Timecards',
            'url' => '/apps/sbaio/timecards',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 40,
            'priority' => 74,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_payroll',
            'feature_key' => 'payroll',
            'label_key' => 'nav.sbaio_payroll',
            'label' => 'Payroll',
            'url' => '/apps/sbaio/payroll',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 50,
            'priority' => 72,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_payroll_parity',
            'feature_key' => 'payroll_parity',
            'label_key' => 'nav.sbaio_payroll_parity',
            'label' => 'Payroll Parity',
            'url' => '/apps/sbaio/payroll/parity',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 55,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_schedules',
            'feature_key' => 'schedules',
            'label_key' => 'nav.sbaio_schedules',
            'label' => 'Schedules',
            'url' => '/apps/sbaio/schedules',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 60,
            'priority' => 62,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_leave',
            'feature_key' => 'leave',
            'label_key' => 'nav.sbaio_leave',
            'label' => 'Leave',
            'url' => '/apps/sbaio/leave',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 70,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_customers',
            'feature_key' => 'customers',
            'label_key' => 'nav.sbaio_customers',
            'label' => 'Customers',
            'url' => '/apps/sbaio/customers',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 80,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_tasks',
            'feature_key' => 'tasks',
            'label_key' => 'nav.sbaio_tasks',
            'label' => 'Tasks',
            'url' => '/apps/sbaio/tasks',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 90,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_sales',
            'feature_key' => 'sales',
            'label_key' => 'nav.sbaio_sales',
            'label' => 'Sales',
            'url' => '/apps/sbaio/sales',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 100,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_expenses',
            'feature_key' => 'expenses',
            'label_key' => 'nav.sbaio_expenses',
            'label' => 'Expenses',
            'url' => '/apps/sbaio/expenses',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 110,
        ],
        [
            'source_key' => 'apps.sbaio.modules',
            'group' => 'Apps',
            'section' => 'SBAIO',
            'module' => 'sbaio',
            'owner' => 'sbaio',
            'key' => 'sbaio_notices',
            'feature_key' => 'notices',
            'label_key' => 'nav.sbaio_notices',
            'label' => 'Notices',
            'url' => '/apps/sbaio/notices',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 120,
        ],
    ],
];
