<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-open.php'; ?>
<div class="card"><div class="row u-style-2d7d2729a4"><h2 class="u-style-1169661891"><?= e(t('module.dispatch_entries.add')) ?></h2><a class="btn" href="/dispatch-entries"><?= e(t('common.back_to_list')) ?></a></div></div>
<?php if (!empty($error ?? '')): ?><div class="card u-style-64e7e2c551"><?= e((string)$error) ?></div><?php endif; ?>
<?php if ($available_stock !== null): ?><div class="card"><div class="muted"><?= e(t('ops.qc_dispatch_edit.available_stock_selected_part')) ?>: <strong><?= e((string)$available_stock) ?></strong></div></div><?php endif; ?>
<div class="card"><div class="muted"><?= e(t('ops.qc_dispatch_edit.dispatch_governance_hint')) ?></div></div>
<div class="card"><form method="post" action="/dispatch-entries/add" class="row"><input type="hidden" name="csrf" value="<?= e(\App\Core\Auth::csrfToken()) ?>">
<div class="u-style-a17b2f9a1e"><label class="muted u-style-98847c28df"><?= e(t('common.date')) ?> *</label><input class="input" type="date" name="dispatch_date" required value="<?= e((string)($old['dispatch_date'] ?? '')) ?>"></div>
<div class="u-style-f308e46b7c"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.daily_order_optional')) ?></label><select name="daily_order_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($daily_orders as $d): ?><option value="<?= (int)$d['id'] ?>" <?= ((int)($old['daily_order_id'] ?? 0) === (int)$d['id']) ? 'selected' : '' ?>>#<?= (int)$d['id'] ?> <?= e((string)$d['customer_name']) ?> (<?= e((string)$d['order_date']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-f308e46b7c"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.production_plan_optional')) ?></label><select name="production_plan_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($production_plans as $pp): ?><option value="<?= (int)$pp['id'] ?>" <?= ((int)($old['production_plan_id'] ?? 0) === (int)$pp['id']) ? 'selected' : '' ?>>#<?= (int)$pp['id'] ?> <?= e((string)$pp['plan_date']) ?> (<?= e((string)$pp['planned_qty']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-f308e46b7c"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.production_entry_optional')) ?></label><select name="production_entry_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($production_entries as $pe): ?><option value="<?= (int)$pe['id'] ?>" <?= ((int)($old['production_entry_id'] ?? 0) === (int)$pe['id']) ? 'selected' : '' ?>>#<?= (int)$pe['id'] ?> <?= e((string)$pe['production_date']) ?> (<?= e(t('ops.qc_dispatch_edit.good_qty')) ?> <?= e((string)$pe['good_qty']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-f308e46b7c"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.qc_entry_optional')) ?></label><select name="qc_entry_id"><option value="0"><?= e(t('ops.qc_dispatch_edit.none')) ?></option><?php foreach ($qc_entries as $q): ?><option value="<?= (int)$q['id'] ?>" <?= ((int)($old['qc_entry_id'] ?? 0) === (int)$q['id']) ? 'selected' : '' ?>>#<?= (int)$q['id'] ?> <?= e(t('ops.qc_dispatch_edit.checked')) ?> <?= e((string)$q['checked_qty']) ?> <?= e(t('ops.qc_dispatch_edit.pass')) ?> <?= e((string)$q['pass_qty']) ?></option><?php endforeach; ?></select></div>
<div class="u-style-b9403873cd"><label class="muted u-style-98847c28df"><?= e(t('common.part')) ?> *</label><select name="product_id" required><option value=""><?= e(t('module.part_machine_map.select_part')) ?></option><?php foreach ($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= ((int)($old['product_id'] ?? 0) === (int)$p['id']) ? 'selected' : '' ?>><?= e((string)$p['parts_name']) ?> (<?= e((string)$p['parts_number']) ?>)</option><?php endforeach; ?></select></div>
<div class="u-style-aae0403196"><label class="muted u-style-98847c28df"><?= e(t('module.dispatch_entries.dispatchable_qty')) ?> *</label><input class="input" type="number" step="0.01" name="dispatchable_qty" required value="<?= e((string)($old['dispatchable_qty'] ?? '')) ?>"></div>
<div class="u-style-2f7ab6d1f3"><label class="muted u-style-98847c28df"><?= e(t('module.dispatch_entries.destination')) ?></label><input class="input" name="destination" value="<?= e((string)($old['destination'] ?? '')) ?>"></div>
<div class="u-style-aae0403196"><label class="muted u-style-98847c28df"><?= e(t('module.dispatch_entries.dispatch_type')) ?></label><input class="input" name="dispatch_type" value="<?= e((string)($old['dispatch_type'] ?? 'Regular')) ?>"></div>
<div class="u-style-a17b2f9a1e"><label class="muted u-style-98847c28df"><?= e(t('module.dispatch_entries.dispatch_status')) ?></label><select name="dispatch_status"><?php foreach (($status_options ?? []) as $value => $label): ?><option value="<?= e((string)$value) ?>" <?= ((string)($old['dispatch_status'] ?? 'Ready') === (string)$value) ? 'selected' : '' ?>><?= e((string)$label) ?></option><?php endforeach; ?></select></div>
<div class="u-style-2f7ab6d1f3"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.workflow_reason')) ?></label><input class="input" name="status_reason" value="<?= e((string)($old['status_reason'] ?? '')) ?>" placeholder="<?= e(t('ops.qc_dispatch_edit.workflow_reason_placeholder')) ?>"></div>
<div class="u-style-4ca11fcb42"><label class="muted u-style-98847c28df"><?= e(t('ops.qc_dispatch_edit.workflow_note')) ?></label><textarea name="status_note" placeholder="<?= e(t('ops.qc_dispatch_edit.workflow_note_placeholder')) ?>"><?= e((string)($old['status_note'] ?? '')) ?></textarea></div>
<div class="u-style-4ca11fcb42"><label class="muted u-style-98847c28df"><?= e(t('common.remarks')) ?></label><textarea name="remarks"><?= e((string)($old['remarks'] ?? '')) ?></textarea></div>
<div class="row u-style-0466783d98"><button class="btn ok" type="submit"><?= e(t('module.dispatch_entries.save')) ?></button><a class="btn" href="/dispatch-entries"><?= e(t('common.cancel')) ?></a></div>
</form></div>
<?php require APP_ROOT . '/public/views/layouts/admin-wrapper-close.php'; ?>
