<?php
return [
    'tool_key' => 'notification_template_designer',
    'key' => 'notification_template_designer',
    'label' => 'Notification Template Designer',
    'name' => 'Notification Template Designer',
    'name_key' => 'studio.tool.notification_template_designer.name',
    'description_key' => 'studio.tool.notification_template_designer.description',
    'category' => 'authoring',
    'home_group' => 'design_content',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/notification-template-designer',
    'placeholder' => true,
    'risk_level' => 'medium',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/notification-template-designer'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['notification_template', 'app', 'module', 'workflow'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
