<?php
declare(strict_types=1);

return [
    'contract' => 'navigation.v1',
    'owner' => 'procurement',
    'items' => [
        [
            'source_key' => 'apps.procurement.dashboard',
            'group' => 'Apps',
            'section' => 'Procurement',
            'module' => 'procurement',
            'owner' => 'procurement',
            'key' => 'procurement_home',
            'feature_key' => 'procurement_home',
            'label' => 'Procurement',
            'url' => '/apps/procurement',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 10,
            'priority' => 90,
            'always_visible' => true,
        ],
        [
            'source_key' => 'apps.procurement.requests',
            'group' => 'Apps',
            'section' => 'Procurement',
            'module' => 'procurement',
            'owner' => 'procurement',
            'key' => 'procurement_requests',
            'feature_key' => 'procurement_requests',
            'label' => 'Requests',
            'url' => '/apps/procurement/requests',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 20,
            'priority' => 86,
        ],
        [
            'source_key' => 'apps.procurement.orders',
            'group' => 'Apps',
            'section' => 'Procurement',
            'module' => 'procurement',
            'owner' => 'procurement',
            'key' => 'procurement_orders',
            'feature_key' => 'procurement_orders',
            'label' => 'Purchase Orders',
            'url' => '/apps/procurement/orders',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 30,
            'priority' => 84,
        ],
        [
            'source_key' => 'apps.procurement.receipts',
            'group' => 'Apps',
            'section' => 'Procurement',
            'module' => 'procurement',
            'owner' => 'procurement',
            'key' => 'procurement_receipts',
            'feature_key' => 'procurement_receipts',
            'label' => 'Receipts',
            'url' => '/apps/procurement/receipts',
            'visible_if' => 'logged_in',
            'nav_visible' => true,
            'order' => 40,
            'priority' => 82,
        ],
    ],
];
