<?php
return [
    'key' => 'app_builder',
    'name' => 'App Builder',
    'name_key' => 'studio.tool.app_builder.name',
    'description_key' => 'studio.tool.app_builder.description',
    'category' => 'authoring',
    'home_group' => 'architecture',
    'status' => 'planned',
    'canonical_route' => '/apps/studio/tools/app-builder',
    'placeholder' => true,
    'risk_level' => 'high',
    'default_enabled' => true,
    'can_disable' => true,
    'required_permissions' => ['studio.manage'],
    'allowed_environments' => ['local', 'staging', 'production'],
    'routes' => ['/apps/studio/tools/app-builder'],
    'views' => ['apps/Studio/Views/pages/tool_placeholder.php'],
    'services' => ['Apps\\Studio\\Controllers\\StudioController::governedToolPlaceholder'],
    'owner' => 'studio',
    'can_load' => ['app'],
    'can_modify' => true,
    'requires_approval' => true,
    'writes_to_owner_artifact' => true,
    'supports_diff' => true,
    'supports_snapshot' => true,
    'supports_rollback' => true,
];
